//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ApprovalStatus
    {
        public int int_ApprovalStatusID { get; set; }
        public int int_ApprovalStatus { get; set; }
        public string var_ApprovalStatus { get; set; }
        public string var_Description { get; set; }
        public string var_Help { get; set; }
    }
}
