//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FDFolders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_FDFolders()
        {
            this.tbl_FDArticles = new HashSet<tbl_FDArticles>();
        }
    
        public long int_FDFolderId { get; set; }
        public Nullable<long> int_FDSolutionId { get; set; }
        public string nvar_Name { get; set; }
        public string nvar_Description { get; set; }
        public System.DateTime dt_CreatedAt { get; set; }
        public Nullable<System.DateTime> dt_UpdateAt { get; set; }
        public Nullable<bool> bit_IsDefault { get; set; }
        public Nullable<long> int_Visibility { get; set; }
        public Nullable<long> int_Position { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_FDArticles> tbl_FDArticles { get; set; }
        public virtual tbl_FDSolutions tbl_FDSolutions { get; set; }
    }
}
