//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ConfRegistrations
    {
        public int int_ConfRegistrationID { get; set; }
        public string var_UserName { get; set; }
        public int int_UserID { get; set; }
        public string var_LastName { get; set; }
        public string var_FirstName { get; set; }
        public string var_DistrictName { get; set; }
        public string var_Email { get; set; }
        public string var_JobTitle { get; set; }
        public string var_Phone { get; set; }
        public bool bit_Active { get; set; }
        public string var_SummerEmail { get; set; }
    
        public virtual tbl_UserProfile tbl_UserProfile { get; set; }
    }
}
