//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PermissionSyncSettings
    {
        public int OrgSvcId { get; set; }
        public string PermissionName { get; set; }
        public string SecurityGroupId { get; set; }
        public int SecurityGroupVersion { get; set; }
        public string PermissionProfileId { get; set; }
        public int PermissionProfileVersion { get; set; }
        public string PermissionSetId { get; set; }
        public int PermissionSetVersion { get; set; }
        public string SecurityScopeId { get; set; }
        public int SecurityScopeVersion { get; set; }
    }
}
