//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ARegOptions
    {
        public int int_ARegOptionID { get; set; }
        public int int_ActivityID { get; set; }
        public int int_RegEnrollmentTypeID { get; set; }
        public float rl_Units { get; set; }
        public float rl_NonMemberPrice { get; set; }
        public float rl_MemberPrice { get; set; }
    
        public virtual tbl_Activities tbl_Activities { get; set; }
        public virtual tbl_RegEnrollmentTypes tbl_RegEnrollmentTypes { get; set; }
    }
}
