//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Grades
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Grades()
        {
            this.tbl_AGrades = new HashSet<tbl_AGrades>();
            this.tbl_CalGrades = new HashSet<tbl_CalGrades>();
            this.tbl_UGrades = new HashSet<tbl_UGrades>();
        }
    
        public int int_GradeID { get; set; }
        public int int_DistrictID { get; set; }
        public string var_Grade { get; set; }
        public int int_Order { get; set; }
        public string var_GradeCode { get; set; }
        public bool bit_Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AGrades> tbl_AGrades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CalGrades> tbl_CalGrades { get; set; }
        public virtual tbl_Districts tbl_Districts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_UGrades> tbl_UGrades { get; set; }
    }
}
