//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CalEntries
    {
        public int int_CalEntryID { get; set; }
        public int int_CalendarID { get; set; }
        public int int_UserID { get; set; }
        public string var_Title { get; set; }
        public string var_Description { get; set; }
        public System.DateTime dt_Date { get; set; }
        public System.DateTime dt_EndDate { get; set; }
        public int int_DurationHours { get; set; }
        public int int_DurationMinutes { get; set; }
        public bool bit_AllDayEvent { get; set; }
        public string var_Type { get; set; }
        public string var_Location { get; set; }
        public int int_ReminderDaysBefore1 { get; set; }
        public int int_ReminderDaysBefore2 { get; set; }
        public string var_LocationCode { get; set; }
    
        public virtual tbl_Calendars tbl_Calendars { get; set; }
        public virtual tbl_UserProfile tbl_UserProfile { get; set; }
    }
}
