//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SIFAgents
    {
        public int int_SIFAgentID { get; set; }
        public string var_AgentName { get; set; }
        public string var_Description { get; set; }
        public string var_ZISURL { get; set; }
        public string var_Zones { get; set; }
        public string var_QueryTitle { get; set; }
        public string var_Mode { get; set; }
        public bool bit_IsRegistered { get; set; }
        public bool bit_IsAsleep { get; set; }
        public string var_SIFObjects { get; set; }
        public bool bit_Active { get; set; }
        public bool bit_IsSubscribed { get; set; }
        public bool bit_IsProvisioned { get; set; }
        public string var_SubscribeObjects { get; set; }
        public string var_PublishObjects { get; set; }
        public int int_DistrictID { get; set; }
        public string var_ProvideObjects { get; set; }
        public bool bit_IsProvided { get; set; }
        public string var_JobTitleBlackList { get; set; }
    }
}
