//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_RegTransactions
    {
        public int int_RegTransactionID { get; set; }
        public int int_UserID { get; set; }
        public int int_LPID { get; set; }
        public int int_ProgramID { get; set; }
        public int int_WebRegID { get; set; }
        public int int_WebTransactionTypeID { get; set; }
        public decimal mon_Amount { get; set; }
        public System.DateTime dt_TransactionDate { get; set; }
        public float rl_SalesTaxRate { get; set; }
        public decimal mon_SalesTax { get; set; }
        public decimal mon_WebRegFee { get; set; }
        public bool bit_DistrictPays { get; set; }
        public int int_RegPaymentTypeID { get; set; }
        public string var_RefNumber { get; set; }
        public string var_Notes { get; set; }
        public string var_BContact { get; set; }
        public string var_BAddress1 { get; set; }
        public string var_BAddress2 { get; set; }
        public string var_BCity { get; set; }
        public string var_BState { get; set; }
        public string var_BZip { get; set; }
        public string var_BPhone { get; set; }
        public string var_CCAuthorizationCode { get; set; }
        public string var_CCTransactionID { get; set; }
        public string var_CCNumber { get; set; }
        public int int_CCExpMonth { get; set; }
        public int int_CCExpYear { get; set; }
        public string var_InvoiceNum { get; set; }
        public string var_CheckNum { get; set; }
        public string var_eBankName { get; set; }
        public string var_eAccountType { get; set; }
        public string var_eRoutingNumber { get; set; }
        public string var_eAccountNumber { get; set; }
        public string var_eAuthorizationCode { get; set; }
        public string var_CCCardCode { get; set; }
        public string enc_CCNumber { get; set; }
        public string enc_eAccountNumber { get; set; }
        public string var_RefNumFromUser { get; set; }
        public string var_CustomerProfileId { get; set; }
        public string var_PaymentProfileId { get; set; }
    
        public virtual tbl_UserProfile tbl_UserProfile { get; set; }
    }
}
