//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Objectives
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Objectives()
        {
            this.tbl_AObjectives = new HashSet<tbl_AObjectives>();
            this.tbl_LPObjectives = new HashSet<tbl_LPObjectives>();
            this.tbl_PlanObjectives = new HashSet<tbl_PlanObjectives>();
        }
    
        public int int_ObjectiveID { get; set; }
        public string var_ObjectiveTitle { get; set; }
        public string var_ObjectiveDesc { get; set; }
        public Nullable<int> int_UserID { get; set; }
        public Nullable<int> int_GoalID { get; set; }
        public Nullable<bool> bit_Active { get; set; }
        public Nullable<System.DateTime> dt_PlanStartDate { get; set; }
        public Nullable<System.DateTime> dt_PlanEndDate { get; set; }
        public int int_PDPID { get; set; }
        public string var_Response01 { get; set; }
        public string var_Response02 { get; set; }
        public string var_Response03 { get; set; }
        public string var_Response04 { get; set; }
        public string var_Response05 { get; set; }
        public string var_Response06 { get; set; }
        public string var_Response07 { get; set; }
        public string var_Response08 { get; set; }
        public string var_Response09 { get; set; }
        public string var_Response10 { get; set; }
        public int int_PDPFormID { get; set; }
        public string var_Status { get; set; }
        public int int_LPID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AObjectives> tbl_AObjectives { get; set; }
        public virtual tbl_Goals tbl_Goals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LPObjectives> tbl_LPObjectives { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PlanObjectives> tbl_PlanObjectives { get; set; }
    }
}
