//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_StandardRecommendations
    {
        public int int_StandardRecommendationID { get; set; }
        public int int_UserID { get; set; }
        public int int_StandardID { get; set; }
        public System.DateTime dt_DateRecommended { get; set; }
        public int int_RecommendedBy { get; set; }
        public string nvar_RecommendationNotes { get; set; }
        public bool bit_IsDeleted { get; set; }
        public Nullable<int> int_DeletedBy { get; set; }
        public Nullable<System.DateTime> dt_DateDeleted { get; set; }
        public string nvar_DeletionNotes { get; set; }
    
        public virtual tbl_Standards tbl_Standards { get; set; }
        public virtual tbl_UserProfile tbl_UserProfile { get; set; }
        public virtual tbl_UserProfile tbl_UserProfile1 { get; set; }
        public virtual tbl_UserProfile tbl_UserProfile2 { get; set; }
    }
}
