//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OASYSRubricCriteria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_OASYSRubricCriteria()
        {
            this.tbl_OASYSCriteriaStandardScores = new HashSet<tbl_OASYSCriteriaStandardScores>();
            this.tbl_OASYSEvidenceCriteria = new HashSet<tbl_OASYSEvidenceCriteria>();
            this.tbl_OASYSRubricCriteriaStandards = new HashSet<tbl_OASYSRubricCriteriaStandards>();
            this.tbl_OASYSRubricCrtieriaScores = new HashSet<tbl_OASYSRubricCrtieriaScores>();
            this.tbl_OASYSRubricDescriptors = new HashSet<tbl_OASYSRubricDescriptors>();
            this.tbl_OASYSArtifacts = new HashSet<tbl_OASYSArtifacts>();
        }
    
        public int int_CriteriaID { get; set; }
        public int int_RubricID { get; set; }
        public string nvar_CriteriaValue { get; set; }
        public int int_CriteriaIndex { get; set; }
        public decimal dec_CriteriaScore { get; set; }
        public string nvar_ExportKey { get; set; }
        public string nvar_Code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSCriteriaStandardScores> tbl_OASYSCriteriaStandardScores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSEvidenceCriteria> tbl_OASYSEvidenceCriteria { get; set; }
        public virtual tbl_OASYSRubrics tbl_OASYSRubrics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSRubricCriteriaStandards> tbl_OASYSRubricCriteriaStandards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSRubricCrtieriaScores> tbl_OASYSRubricCrtieriaScores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSRubricDescriptors> tbl_OASYSRubricDescriptors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSArtifacts> tbl_OASYSArtifacts { get; set; }
    }
}
