//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PlanObjectives
    {
        public int int_PlanObjectiveID { get; set; }
        public int int_PlanID { get; set; }
        public int int_ObjectiveID { get; set; }
    
        public virtual tbl_Objectives tbl_Objectives { get; set; }
        public virtual tbl_Plans tbl_Plans { get; set; }
    }
}
