//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Districts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Districts()
        {
            this.tbl_Activities = new HashSet<tbl_Activities>();
            this.tbl_ActivityFormats = new HashSet<tbl_ActivityFormats>();
            this.tbl_Buildings = new HashSet<tbl_Buildings>();
            this.tbl_Categories = new HashSet<tbl_Categories>();
            this.tbl_CLicensesGroup = new HashSet<tbl_CLicensesGroup>();
            this.tbl_CourseCodes = new HashSet<tbl_CourseCodes>();
            this.tbl_Departments = new HashSet<tbl_Departments>();
            this.tbl_DistrictAbsenceConfig = new HashSet<tbl_DistrictAbsenceConfig>();
            this.tbl_DistrictNews = new HashSet<tbl_DistrictNews>();
            this.tbl_DProviders = new HashSet<tbl_DProviders>();
            this.tbl_DRegionalProviders = new HashSet<tbl_DRegionalProviders>();
            this.tbl_DRenewalLog = new HashSet<tbl_DRenewalLog>();
            this.tbl_EndangeredCustomers = new HashSet<tbl_EndangeredCustomers>();
            this.tbl_EvalMethods = new HashSet<tbl_EvalMethods>();
            this.tbl_Events = new HashSet<tbl_Events>();
            this.tbl_FeatureFlags = new HashSet<tbl_FeatureFlags>();
            this.tbl_Files = new HashSet<tbl_Files>();
            this.tbl_FollowUps = new HashSet<tbl_FollowUps>();
            this.tbl_FundingSources = new HashSet<tbl_FundingSources>();
            this.tbl_Goals = new HashSet<tbl_Goals>();
            this.tbl_Grades = new HashSet<tbl_Grades>();
            this.tbl_Groups = new HashSet<tbl_Groups>();
            this.tbl_Hosts = new HashSet<tbl_Hosts>();
            this.tbl_LearningPlan = new HashSet<tbl_LearningPlan>();
            this.tbl_Locations = new HashSet<tbl_Locations>();
            this.tbl_LogDetail = new HashSet<tbl_LogDetail>();
            this.tbl_OASYSArchiveFormsRequest = new HashSet<tbl_OASYSArchiveFormsRequest>();
            this.tbl_OASYSArtifactGroups = new HashSet<tbl_OASYSArtifactGroups>();
            this.tbl_OASYSCesaScoreExtractConfig = new HashSet<tbl_OASYSCesaScoreExtractConfig>();
            this.tbl_OASYSComponents = new HashSet<tbl_OASYSComponents>();
            this.tbl_OASYSComponentTemplates = new HashSet<tbl_OASYSComponentTemplates>();
            this.tbl_OASYSConversionSheets = new HashSet<tbl_OASYSConversionSheets>();
            this.tbl_OASYSCustomSections = new HashSet<tbl_OASYSCustomSections>();
            this.tbl_OASYSForms = new HashSet<tbl_OASYSForms>();
            this.tbl_OASYSImportTemplates = new HashSet<tbl_OASYSImportTemplates>();
            this.tbl_OASYSMaScoreExtractConfig = new HashSet<tbl_OASYSMaScoreExtractConfig>();
            this.tbl_OASYSNyScoreExtractConfig = new HashSet<tbl_OASYSNyScoreExtractConfig>();
            this.tbl_OASYSNyScoreExtractHediRanges = new HashSet<tbl_OASYSNyScoreExtractHediRanges>();
            this.tbl_OASYSRiScoreExtractConfig = new HashSet<tbl_OASYSRiScoreExtractConfig>();
            this.tbl_OASYSRubrics = new HashSet<tbl_OASYSRubrics>();
            this.tbl_OASYSTeamExportLogEntries = new HashSet<tbl_OASYSTeamExportLogEntries>();
            this.tbl_OASYSTripodCategories = new HashSet<tbl_OASYSTripodCategories>();
            this.tbl_OASYSTripodGroups = new HashSet<tbl_OASYSTripodGroups>();
            this.tbl_OASYSTripodLevels = new HashSet<tbl_OASYSTripodLevels>();
            this.tbl_OASYSTypes = new HashSet<tbl_OASYSTypes>();
            this.tbl_PaymentFormats = new HashSet<tbl_PaymentFormats>();
            this.tbl_Plans = new HashSet<tbl_Plans>();
            this.tbl_PositionTypes = new HashSet<tbl_PositionTypes>();
            this.tbl_Prefs = new HashSet<tbl_Prefs>();
            this.tbl_Programs = new HashSet<tbl_Programs>();
            this.tbl_ProgramSubscribers = new HashSet<tbl_ProgramSubscribers>();
            this.tbl_PromoCodes = new HashSet<tbl_PromoCodes>();
            this.tbl_Purposes = new HashSet<tbl_Purposes>();
            this.tbl_RegCourseProviders = new HashSet<tbl_RegCourseProviders>();
            this.tbl_RegDCourseGrades = new HashSet<tbl_RegDCourseGrades>();
            this.tbl_RegDEnrollmentTypes = new HashSet<tbl_RegDEnrollmentTypes>();
            this.tbl_RegDPaymentTypes = new HashSet<tbl_RegDPaymentTypes>();
            this.tbl_Regions = new HashSet<tbl_Regions>();
            this.tbl_RegTransactionTypes = new HashSet<tbl_RegTransactionTypes>();
            this.tbl_Reports = new HashSet<tbl_Reports>();
            this.tbl_Roles = new HashSet<tbl_Roles>();
            this.tbl_SalarySteps = new HashSet<tbl_SalarySteps>();
            this.tbl_SessionsActive = new HashSet<tbl_SessionsActive>();
            this.tbl_SupportActive = new HashSet<tbl_SupportActive>();
            this.tbl_SupportArchive = new HashSet<tbl_SupportArchive>();
            this.tbl_Surveys = new HashSet<tbl_Surveys>();
            this.tbl_TeachingStandards = new HashSet<tbl_TeachingStandards>();
            this.tbl_UserProfile = new HashSet<tbl_UserProfile>();
            this.tbl_WorkAreas = new HashSet<tbl_WorkAreas>();
            this.tbl_OASYSAdHocReports = new HashSet<tbl_OASYSAdHocReports>();
            this.tbl_Regions1 = new HashSet<tbl_Regions>();
        }
    
        public int int_DistrictID { get; set; }
        public string var_DistrictName { get; set; }
        public string var_DistrictCity { get; set; }
        public string var_DistrictState { get; set; }
        public string var_DistrictZip { get; set; }
        public string var_DistrictPhone { get; set; }
        public string var_DistrictAddress1 { get; set; }
        public string var_DistrictAddress2 { get; set; }
        public string var_DistrictContact { get; set; }
        public string var_DistrictPlanPath { get; set; }
        public int int_NumOfAuthorizedUsers { get; set; }
        public bool bit_FilterActivities { get; set; }
        public int int_PDEProviderNum { get; set; }
        public string var_PDEPassword { get; set; }
        public int rl_CreditsToHours { get; set; }
        public int int_StateID { get; set; }
        public int int_Act48PurposeID { get; set; }
        public bool bit_WebRegEmail { get; set; }
        public string var_CertLogoPath { get; set; }
        public bool bit_DisplayInCustomerList { get; set; }
        public string var_BOCESBackup { get; set; }
        public bool bit_IsMLP { get; set; }
        public bool bit_ChangePassword { get; set; }
        public bool bit_ChangeUserName { get; set; }
        public bool bit_IsRegCustomer { get; set; }
        public bool bit_IsRegionalProvider { get; set; }
        public bool bit_CatalogSearchTerm { get; set; }
        public bool bit_CatalogSearchPurposes { get; set; }
        public bool bit_CatalogSearchGoals { get; set; }
        public bool bit_CatalogSearchStandards { get; set; }
        public bool bit_CatalogSearchInstructors { get; set; }
        public bool bit_CatalogShowInstructors { get; set; }
        public bool bit_CatalogShowStandards { get; set; }
        public bool bit_CatalogShowRegistrationFee { get; set; }
        public int int_ActiveUsers { get; set; }
        public int int_ActiveInstrUsers { get; set; }
        public int int_TotalUsers { get; set; }
        public bool bit_WebRegUseHeader { get; set; }
        public string var_WebRegLogoFile { get; set; }
        public string var_WebRegReturnURL { get; set; }
        public string var_WebRegHeaderColor { get; set; }
        public string var_WebRegLeftNavColor { get; set; }
        public string var_DistrictEmail { get; set; }
        public decimal mon_WebRegFee { get; set; }
        public int int_MinDaysApp { get; set; }
        public int int_MaxDaysApp { get; set; }
        public int int_MinDaysImpact { get; set; }
        public int int_MaxDaysImpact { get; set; }
        public int int_ApplicationFormID { get; set; }
        public int int_ImpactFormID { get; set; }
        public int int_MinDaysMarkComplete { get; set; }
        public int int_MaxDaysMarkComplete { get; set; }
        public string var_GMTOffset { get; set; }
        public bool bit_IsWebHostCustomer { get; set; }
        public bool bit_CatalogSearchCategories { get; set; }
        public string var_TranscriptSignatures { get; set; }
        public bool bit_IsEmailCustomer { get; set; }
        public bool bit_UseWorkflow { get; set; }
        public int int_SessionTimeoutMin { get; set; }
        public bool bit_UseLocations { get; set; }
        public string var_DataExchangePassword { get; set; }
        public bool bit_CatalogSearchPrograms { get; set; }
        public bool bit_IsFileUploadCustomer { get; set; }
        public bool bit_IsFileUploadUsers { get; set; }
        public int int_DistrictStorageSpaceMB { get; set; }
        public int int_UserStorageSpaceMB { get; set; }
        public bool bit_IsCalendarCustomer { get; set; }
        public string chr_DistrictOptions { get; set; }
        public bool bit_CatalogSearchLocations { get; set; }
        public bool bit_CheckUserProfile { get; set; }
        public int int_AdminID { get; set; }
        public int int_Admin2ID { get; set; }
        public string var_BillingContact { get; set; }
        public string var_CountyCode { get; set; }
        public string var_DistrictCode { get; set; }
        public string var_DistrictType { get; set; }
        public bool bit_CatalogShowLocation { get; set; }
        public bool bit_CatalogShowEnrollment { get; set; }
        public bool bit_CatalogShowDescription { get; set; }
        public string var_CatalogSortBy { get; set; }
        public bool bit_CatalogSearchActivityFormats { get; set; }
        public bool bit_CatalogShowSearchDates { get; set; }
        public string var_RegionCode { get; set; }
        public string txt_WebRegTermsHTML { get; set; }
        public string var_AbsenceProviderName { get; set; }
        public string var_AbsenceCustomerID { get; set; }
        public string var_AbsenceSubShifts { get; set; }
        public bool bit_CatalogSearchCourseCodes { get; set; }
        public int int_DropMinDays { get; set; }
        public bool bit_CatalogShowAdvSearch { get; set; }
        public bool bit_WebRegUseCalendar { get; set; }
        public System.DateTime dt_DateUpdated { get; set; }
        public bool bit_TEACHUploadEnabled { get; set; }
        public bool bit_IsOASYSCustomer { get; set; }
        public string var_DOEUsername { get; set; }
        public string var_DOEPassword { get; set; }
        public string var_DNCESID { get; set; }
        public int int_TechUserID { get; set; }
        public string var_LdapConfig { get; set; }
        public int int_SecurityTypeID { get; set; }
        public string var_SamlConfig { get; set; }
        public string var_SubFinderURL { get; set; }
        public string var_SubFinderPassword { get; set; }
        public int int_FreshDeskID { get; set; }
        public string var_StateScoringCode { get; set; }
        public bool bit_DisableDailyEmails { get; set; }
        public int int_OasysUserID { get; set; }
        public int int_ElevateUserID { get; set; }
        public int int_SHPUserID { get; set; }
        public string var_AltDisplayName { get; set; }
        public bool bit_CatalogSearchSessionCode { get; set; }
        public bool bit_CatalogShowYearLong { get; set; }
        public string var_RemoteSysName { get; set; }
        public string var_RemoteSysID { get; set; }
        public int int_TranscriptUserID { get; set; }
        public bool bit_IsContentCustomer { get; set; }
        public bool bit_IsMyVideoCustomer { get; set; }
        public bool bit_IsVideoChannelCustomer { get; set; }
        public int int_FLOrgID { get; set; }
        public bool bit_IDMEnabled { get; set; }
        public bool bit_MigrationEnabled { get; set; }
        public bool bit_UserServiceSyncEnabled { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Activities> tbl_Activities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ActivityFormats> tbl_ActivityFormats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Buildings> tbl_Buildings { get; set; }
        public virtual tbl_CatalogOptions tbl_CatalogOptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Categories> tbl_Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CLicensesGroup> tbl_CLicensesGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CourseCodes> tbl_CourseCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Departments> tbl_Departments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DistrictAbsenceConfig> tbl_DistrictAbsenceConfig { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DistrictNews> tbl_DistrictNews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DProviders> tbl_DProviders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DRegionalProviders> tbl_DRegionalProviders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DRenewalLog> tbl_DRenewalLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_EndangeredCustomers> tbl_EndangeredCustomers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_EvalMethods> tbl_EvalMethods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Events> tbl_Events { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_FeatureFlags> tbl_FeatureFlags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Files> tbl_Files { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_FollowUps> tbl_FollowUps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_FundingSources> tbl_FundingSources { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Goals> tbl_Goals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Grades> tbl_Grades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Groups> tbl_Groups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Hosts> tbl_Hosts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LearningPlan> tbl_LearningPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Locations> tbl_Locations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LogDetail> tbl_LogDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSArchiveFormsRequest> tbl_OASYSArchiveFormsRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSArtifactGroups> tbl_OASYSArtifactGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSCesaScoreExtractConfig> tbl_OASYSCesaScoreExtractConfig { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSComponents> tbl_OASYSComponents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSComponentTemplates> tbl_OASYSComponentTemplates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSConversionSheets> tbl_OASYSConversionSheets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSCustomSections> tbl_OASYSCustomSections { get; set; }
        public virtual tbl_OASYSDistrictSettings tbl_OASYSDistrictSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSForms> tbl_OASYSForms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSImportTemplates> tbl_OASYSImportTemplates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSMaScoreExtractConfig> tbl_OASYSMaScoreExtractConfig { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSNyScoreExtractConfig> tbl_OASYSNyScoreExtractConfig { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSNyScoreExtractHediRanges> tbl_OASYSNyScoreExtractHediRanges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSRiScoreExtractConfig> tbl_OASYSRiScoreExtractConfig { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSRubrics> tbl_OASYSRubrics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSTeamExportLogEntries> tbl_OASYSTeamExportLogEntries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSTripodCategories> tbl_OASYSTripodCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSTripodGroups> tbl_OASYSTripodGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSTripodLevels> tbl_OASYSTripodLevels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSTypes> tbl_OASYSTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PaymentFormats> tbl_PaymentFormats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Plans> tbl_Plans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PositionTypes> tbl_PositionTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Prefs> tbl_Prefs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Programs> tbl_Programs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ProgramSubscribers> tbl_ProgramSubscribers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PromoCodes> tbl_PromoCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Purposes> tbl_Purposes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_RegCourseProviders> tbl_RegCourseProviders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_RegDCourseGrades> tbl_RegDCourseGrades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_RegDEnrollmentTypes> tbl_RegDEnrollmentTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_RegDPaymentTypes> tbl_RegDPaymentTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Regions> tbl_Regions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_RegTransactionTypes> tbl_RegTransactionTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Reports> tbl_Reports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Roles> tbl_Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SalarySteps> tbl_SalarySteps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SessionsActive> tbl_SessionsActive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SupportActive> tbl_SupportActive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SupportArchive> tbl_SupportArchive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Surveys> tbl_Surveys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TeachingStandards> tbl_TeachingStandards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_UserProfile> tbl_UserProfile { get; set; }
        public virtual tbl_WebRegDistrictSettings tbl_WebRegDistrictSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_WorkAreas> tbl_WorkAreas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSAdHocReports> tbl_OASYSAdHocReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Regions> tbl_Regions1 { get; set; }
    }
}
