//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OASYSConversionSheets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_OASYSConversionSheets()
        {
            this.tbl_OASYSConversionSheetRanges = new HashSet<tbl_OASYSConversionSheetRanges>();
            this.tbl_OASYSSlos = new HashSet<tbl_OASYSSlos>();
        }
    
        public int int_ConversionSheetID { get; set; }
        public string nvar_Name { get; set; }
        public int int_DistrictID { get; set; }
        public bool bit_IsDeleted { get; set; }
        public bool bit_IsSLO { get; set; }
    
        public virtual tbl_Districts tbl_Districts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSConversionSheetRanges> tbl_OASYSConversionSheetRanges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSSlos> tbl_OASYSSlos { get; set; }
    }
}
