//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OASYSRiScoreExtractFieldConfig
    {
        public int int_ID { get; set; }
        public int int_PanelConfigID { get; set; }
        public string nvar_FieldName { get; set; }
        public string nvar_ComponentBoxID { get; set; }
        public string nvar_ComponentBoxValue { get; set; }
        public string nvar_ElementBoxID { get; set; }
        public string nvar_ElementBoxValue { get; set; }
        public string nvar_SectionBoxID { get; set; }
        public string nvar_SectionBoxValue { get; set; }
    
        public virtual tbl_OASYSRiScoreExtractPanelConfig tbl_OASYSRiScoreExtractPanelConfig { get; set; }
    }
}
