//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ActivityEvents
    {
        public int int_ActivityEventId { get; set; }
        public System.DateTime dt_TimeStamp { get; set; }
        public string var_Description { get; set; }
        public string var_Notes { get; set; }
        public string var_Type { get; set; }
        public string var_Status { get; set; }
        public int int_UserId { get; set; }
        public int int_ActivityId { get; set; }
        public Nullable<int> int_LearningPlanId { get; set; }
        public int int_DistrictId { get; set; }
    
        public virtual tbl_Activities tbl_Activities { get; set; }
    }
}
