//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Comments
    {
        public int int_CommentID { get; set; }
        public int int_ID { get; set; }
        public string var_TableName { get; set; }
        public System.DateTime dt_TimeStamp { get; set; }
        public System.DateTime dt_LastUpdated { get; set; }
        public string var_Type { get; set; }
        public string var_Status { get; set; }
        public string var_Description { get; set; }
        public string txt_Notes { get; set; }
        public string var_Title { get; set; }
        public string var_ConfirmationID { get; set; }
        public int int_UserID { get; set; }
    
        public virtual tbl_UserProfile tbl_UserProfile { get; set; }
    }
}
