//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OASYSUserComponents
    {
        public int int_ComponentUserID { get; set; }
        public int int_ComponentID { get; set; }
        public int int_UserID { get; set; }
        public Nullable<System.DateTime> dt_ScheduledDate { get; set; }
        public bool bit_ScheduleRequestApproved { get; set; }
        public Nullable<int> int_ScheduleRequestUserID { get; set; }
        public Nullable<System.DateTime> dt_CompletedDate { get; set; }
        public string nvar_Notes { get; set; }
        public int int_Duration { get; set; }
    
        public virtual tbl_OASYSComponents tbl_OASYSComponents { get; set; }
        public virtual tbl_UserProfile tbl_UserProfile { get; set; }
        public virtual tbl_UserProfile tbl_UserProfile1 { get; set; }
    }
}
