//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ListPrefs
    {
        public int int_ListPrefID { get; set; }
        public int int_UserID { get; set; }
        public string var_ViewName { get; set; }
        public string var_SectionIDs { get; set; }
        public string var_FieldNames { get; set; }
        public string var_Filters { get; set; }
        public string var_Sizes { get; set; }
        public string var_SortCol { get; set; }
        public string var_SortDir { get; set; }
        public int int_PageNumber { get; set; }
        public int int_PageSize { get; set; }
    
        public virtual tbl_UserProfile tbl_UserProfile { get; set; }
    }
}
