//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UserPersonAssociations
    {
        public int int_PersonAssocId { get; set; }
        public int int_UserId { get; set; }
        public System.Guid gd_PersonId { get; set; }
        public System.Guid gd_OrgPersonId { get; set; }
    
        public virtual tbl_UserProfile tbl_UserProfile { get; set; }
    }
}
