//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SecurityTypes
    {
        public int int_SecurityTypeId { get; set; }
        public string var_Name { get; set; }
        public string var_Description { get; set; }
        public int int_MinLength { get; set; }
        public Nullable<int> int_ExpirationMonths { get; set; }
        public int int_RequiredCategories { get; set; }
        public int int_LowersRequired { get; set; }
        public int int_UppersRequired { get; set; }
        public int int_NumbersRequired { get; set; }
        public int int_SpecialsRequired { get; set; }
    
        public virtual tbl_SecurityTypes tbl_SecurityTypes1 { get; set; }
        public virtual tbl_SecurityTypes tbl_SecurityTypes2 { get; set; }
    }
}
