//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CPublishers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_CPublishers()
        {
            this.tbl_CCatalog = new HashSet<tbl_CCatalog>();
        }
    
        public int int_CPublisherID { get; set; }
        public string var_Name { get; set; }
        public string var_Address1 { get; set; }
        public string var_Address2 { get; set; }
        public string var_City { get; set; }
        public string var_State { get; set; }
        public string var_Zip { get; set; }
        public string var_ID { get; set; }
        public string var_URL { get; set; }
        public string var_Contact { get; set; }
        public string var_Phone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CCatalog> tbl_CCatalog { get; set; }
    }
}
