//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DProviders
    {
        public int int_DProvidersID { get; set; }
        public int int_ProviderID { get; set; }
        public int int_DistrictID { get; set; }
    
        public virtual tbl_Districts tbl_Districts { get; set; }
        public virtual tbl_Providers tbl_Providers { get; set; }
    }
}
