//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AdminRights
    {
        public int int_AdminRightsID { get; set; }
        public int int_AdminRight { get; set; }
        public string var_AdminRight { get; set; }
        public string var_Category { get; set; }
        public int int_Order { get; set; }
        public string var_URLReferral { get; set; }
        public string var_Description { get; set; }
        public string var_ShortName { get; set; }
        public bool bit_ShowInLeftNav { get; set; }
    }
}
