//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FileTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_FileTypes()
        {
            this.tbl_Files = new HashSet<tbl_Files>();
        }
    
        public int int_FileTypeID { get; set; }
        public string var_Name { get; set; }
        public string var_Description { get; set; }
        public string var_ExampleFileName { get; set; }
        public bool bit_IsPersonal { get; set; }
        public bool bit_IsPublic { get; set; }
        public string var_Type { get; set; }
        public bool bit_Active { get; set; }
        public string var_FileExtensions { get; set; }
        public bool bit_SysAdminOnly { get; set; }
        public bool bit_DistrictConfigOnly { get; set; }
        public bool bit_DistrictAdminOnly { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Files> tbl_Files { get; set; }
    }
}
