//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EmailOptions
    {
        public int int_EmailOptionID { get; set; }
        public int int_UserID { get; set; }
        public string var_FromName { get; set; }
        public string var_ReplyTo { get; set; }
        public string var_DescendingDate { get; set; }
        public string var_MessagesPerPage { get; set; }
        public string var_AutoSaveSent { get; set; }
        public string var_AutoBulkMail { get; set; }
        public string var_AutoNextMessage { get; set; }
        public string var_ForwardInline { get; set; }
        public string var_ReplyInclude { get; set; }
        public string var_WarnWithoutSubject { get; set; }
        public string var_WarnEmptyMessage { get; set; }
        public string var_Signature { get; set; }
        public bool bit_AutoSignature { get; set; }
        public string var_VacationResponse { get; set; }
        public bool bit_VacationOn { get; set; }
    
        public virtual tbl_UserProfile tbl_UserProfile { get; set; }
    }
}
