//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OASYSRubricCriteriaStandards
    {
        public int int_CriteriaID { get; set; }
        public int int_StandardID { get; set; }
        public int int_ScoreThreshold { get; set; }
        public bool bit_IsDeleted { get; set; }
    
        public virtual tbl_OASYSRubricCriteria tbl_OASYSRubricCriteria { get; set; }
        public virtual tbl_Standards tbl_Standards { get; set; }
    }
}
