//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CSessions
    {
        public int int_CSessionID { get; set; }
        public int int_CBundleID { get; set; }
        public int int_UserID { get; set; }
        public int int_LearningPlanID { get; set; }
        public string var_Bookmark { get; set; }
        public string var_Status { get; set; }
        public int int_Score { get; set; }
        public string var_Time { get; set; }
        public string txt_Request { get; set; }
    
        public virtual tbl_CBundles tbl_CBundles { get; set; }
        public virtual tbl_LearningPlan tbl_LearningPlan { get; set; }
    }
}
