//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_APurposes
    {
        public int int_APurposeID { get; set; }
        public int int_ActivityID { get; set; }
        public int int_PurposeID { get; set; }
        public float rl_PHours { get; set; }
        public float rl_PCredits { get; set; }
    
        public virtual tbl_Activities tbl_Activities { get; set; }
        public virtual tbl_Purposes tbl_Purposes { get; set; }
    }
}
