//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UMentors
    {
        public int int_UMentorID { get; set; }
        public int int_MentorUserID { get; set; }
        public int int_MenteeUserID { get; set; }
        public Nullable<System.DateTime> dt_StartDate { get; set; }
        public Nullable<System.DateTime> dt_EndDate { get; set; }
        public bool bit_Active { get; set; }
    
        public virtual tbl_UserProfile tbl_UserProfile { get; set; }
        public virtual tbl_UserProfile tbl_UserProfile1 { get; set; }
    }
}
