//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DistrictAbsenceConfig
    {
        public int int_DistrictAbsenceConfigId { get; set; }
        public int int_DistrictId { get; set; }
        public int int_AbsenceProvider { get; set; }
        public string var_AbsenceCustomerId { get; set; }
        public string var_AbsenceWebServiceKey { get; set; }
        public bool bit_UsesAccountingCodes { get; set; }
        public bool bit_UsesDuration { get; set; }
        public string var_AbsenceDefaultType { get; set; }
        public string var_AbsenceHoldValue { get; set; }
        public string var_AbsenceNoSubType { get; set; }
        public bool bit_UsesSubOnlyTracking { get; set; }
    
        public virtual tbl_Districts tbl_Districts { get; set; }
    }
}
