//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Lists
    {
        public int int_ListID { get; set; }
        public string var_Fieldname { get; set; }
        public string var_Name { get; set; }
        public string var_Value { get; set; }
        public int int_Order { get; set; }
        public bool bit_Active { get; set; }
    }
}
