//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CCatalog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_CCatalog()
        {
            this.tbl_CBundles = new HashSet<tbl_CBundles>();
            this.tbl_CLicensesGroup = new HashSet<tbl_CLicensesGroup>();
            this.tbl_CLicensesIndividual = new HashSet<tbl_CLicensesIndividual>();
        }
    
        public int int_CCatalogID { get; set; }
        public string var_Title { get; set; }
        public string var_Description { get; set; }
        public float rl_Hours { get; set; }
        public float rl_Credits { get; set; }
        public decimal mon_PriceIndividual { get; set; }
        public decimal mon_PriceGroup { get; set; }
        public int int_CPublisherID { get; set; }
        public string var_URL { get; set; }
        public bool bit_URLIsValid { get; set; }
        public bool bit_Active { get; set; }
        public int int_Order { get; set; }
        public string var_HTML { get; set; }
        public int int_OnHand { get; set; }
        public bool bit_TrackInventory { get; set; }
        public string var_Status { get; set; }
        public string var_PhotoFileName { get; set; }
        public string var_Version { get; set; }
        public string var_Features { get; set; }
        public string var_Requirements { get; set; }
        public string var_Audience { get; set; }
        public string var_SummaryHTML { get; set; }
        public bool bit_DisplayInCatalog { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CBundles> tbl_CBundles { get; set; }
        public virtual tbl_CPublishers tbl_CPublishers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CLicensesGroup> tbl_CLicensesGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CLicensesIndividual> tbl_CLicensesIndividual { get; set; }
    }
}
