//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OASYSUnalignedEvidences
    {
        public int int_EvidenceID { get; set; }
        public int int_UserID { get; set; }
        public int int_FormID { get; set; }
        public int int_InstanceID { get; set; }
        public int int_EvaluationID { get; set; }
        public string nvar_Name { get; set; }
        public System.DateTime dt_RecordDate { get; set; }
        public int int_AdminID { get; set; }
    
        public virtual tbl_OASYSEvaluations tbl_OASYSEvaluations { get; set; }
        public virtual tbl_OASYSForms tbl_OASYSForms { get; set; }
        public virtual tbl_UserProfile tbl_UserProfile { get; set; }
        public virtual tbl_UserProfile tbl_UserProfile1 { get; set; }
    }
}
