//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_RegQuarterlyTransactions
    {
        public int RegQuarterlyTransactionID { get; set; }
        public Nullable<int> ActivityID { get; set; }
        public Nullable<int> WebRegID { get; set; }
        public Nullable<int> LearningPlanID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string CourseCode { get; set; }
        public Nullable<int> CourseCodeName { get; set; }
        public string SessionCode { get; set; }
        public Nullable<System.DateTime> dt_StartDate { get; set; }
        public Nullable<System.DateTime> dt_EndDate { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public string ActivityTitle { get; set; }
        public string SubmissionDate { get; set; }
        public string DateCompleted { get; set; }
        public Nullable<int> ApprovalStatus { get; set; }
        public string EnrollmentOption { get; set; }
        public string PaymentType { get; set; }
        public Nullable<bool> SubRequired { get; set; }
        public Nullable<float> HoursAttended { get; set; }
        public Nullable<float> Credits { get; set; }
        public string EnrollmentStatus { get; set; }
        public string EnrollmentStatusCode { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string CollegeInfo { get; set; }
        public string Phone { get; set; }
        public string BuildingAssignment { get; set; }
        public Nullable<bool> RequiresPhysicalAssistance { get; set; }
        public string CertificateID { get; set; }
        public Nullable<bool> IsUsCitizen { get; set; }
        public Nullable<bool> IsHispanic { get; set; }
        public string Race { get; set; }
        public string DistrictName { get; set; }
        public string DistrictAddress1 { get; set; }
        public string DisrictAddress2 { get; set; }
        public string DistrictCity { get; set; }
        public string DistrictState { get; set; }
        public string DistrictPostalCode { get; set; }
        public string DistrictPhone { get; set; }
        public string RegionCode { get; set; }
        public string CountyCode { get; set; }
        public string DistrictCode { get; set; }
        public string DistrictContact { get; set; }
        public Nullable<decimal> TransactionFee { get; set; }
        public string DistrictUsesMLP { get; set; }
        public string UserUsesMLP { get; set; }
        public string ProgramName { get; set; }
        public string ProgramCode { get; set; }
        public string ProgramEmail { get; set; }
        public string ProgramBillingName { get; set; }
        public string ProviderName { get; set; }
        public string RegistrationType { get; set; }
        public Nullable<int> BillingYear { get; set; }
        public string BillingQuarter { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public Nullable<int> ProgramID { get; set; }
        public string WebRegDistrictName { get; set; }
    
        public virtual tbl_UserProfile tbl_UserProfile { get; set; }
    }
}
