//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Events
    {
        public int int_EventID { get; set; }
        public int int_DistrictID { get; set; }
        public string var_Name { get; set; }
        public string var_Description { get; set; }
        public string var_Instructions { get; set; }
        public System.DateTime dt_StartDate { get; set; }
        public System.DateTime dt_EndDate { get; set; }
        public System.DateTime dt_EnrollmentDeadline { get; set; }
        public bool bit_DisplayOnMenu { get; set; }
        public bool bit_IsConference { get; set; }
        public System.DateTime dt_StartShowing { get; set; }
        public System.DateTime dt_StopShowing { get; set; }
        public int int_ProgramID { get; set; }
        public decimal mon_RegistrationFee { get; set; }
        public bool bit_Active { get; set; }
    
        public virtual tbl_Districts tbl_Districts { get; set; }
    }
}
