//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FDArticles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_FDArticles()
        {
            this.tbl_FDMetaKeywords = new HashSet<tbl_FDMetaKeywords>();
        }
    
        public long int_FDArticleId { get; set; }
        public string nvar_Title { get; set; }
        public string nvar_DescHtml { get; set; }
        public Nullable<long> int_FDFolderId { get; set; }
        public Nullable<long> int_UserId { get; set; }
        public Nullable<System.DateTime> dt_UpdatedAt { get; set; }
        public Nullable<bool> bit_Delta { get; set; }
        public Nullable<bool> bit_Status { get; set; }
        public Nullable<long> int_ThumbsUp { get; set; }
        public Nullable<long> int_ThumbsDown { get; set; }
        public Nullable<long> int_ArtType { get; set; }
        public string nvar_DescUnHtml { get; set; }
    
        public virtual tbl_FDFolders tbl_FDFolders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_FDMetaKeywords> tbl_FDMetaKeywords { get; set; }
    }
}
