//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EmailAddressBook
    {
        public int int_EmailAddressBookID { get; set; }
        public int int_UserID { get; set; }
        public string var_EmailAddress { get; set; }
        public string var_NickName { get; set; }
        public string var_FirstName { get; set; }
        public string var_LastName { get; set; }
        public string var_Organization { get; set; }
        public string var_OfficePhone { get; set; }
        public string var_HomePhone { get; set; }
        public string var_MobilePhone { get; set; }
        public string var_Fax { get; set; }
        public string var_Notes { get; set; }
        public int int_Order { get; set; }
        public int int_EmailCategoryID { get; set; }
    
        public virtual tbl_EmailCategories tbl_EmailCategories { get; set; }
    }
}
