//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UserProfile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_UserProfile()
        {
            this.tbl_AInstructors = new HashSet<tbl_AInstructors>();
            this.tbl_CalAdmins = new HashSet<tbl_CalAdmins>();
            this.tbl_CalEntries = new HashSet<tbl_CalEntries>();
            this.tbl_Comments = new HashSet<tbl_Comments>();
            this.tbl_ConfPrefFeatures = new HashSet<tbl_ConfPrefFeatures>();
            this.tbl_ConfRegistrations = new HashSet<tbl_ConfRegistrations>();
            this.tbl_ConfSessionProposals = new HashSet<tbl_ConfSessionProposals>();
            this.tbl_ConfSPropVotes = new HashSet<tbl_ConfSPropVotes>();
            this.tbl_DailyEmail = new HashSet<tbl_DailyEmail>();
            this.tbl_DailyEMail_PRE = new HashSet<tbl_DailyEMail_PRE>();
            this.tbl_Departments = new HashSet<tbl_Departments>();
            this.tbl_DevelopmentRequests = new HashSet<tbl_DevelopmentRequests>();
            this.tbl_EmailOptions = new HashSet<tbl_EmailOptions>();
            this.tbl_FundingUsers = new HashSet<tbl_FundingUsers>();
            this.tbl_LearningPlan = new HashSet<tbl_LearningPlan>();
            this.tbl_ListPrefs = new HashSet<tbl_ListPrefs>();
            this.tbl_LogDetail = new HashSet<tbl_LogDetail>();
            this.tbl_LPApprovals = new HashSet<tbl_LPApprovals>();
            this.tbl_OASYSAdHocReportActivity = new HashSet<tbl_OASYSAdHocReportActivity>();
            this.tbl_OASYSArchiveFormsRequest = new HashSet<tbl_OASYSArchiveFormsRequest>();
            this.tbl_OASYSArtifacts = new HashSet<tbl_OASYSArtifacts>();
            this.tbl_OASYSComponentUserRights = new HashSet<tbl_OASYSComponentUserRights>();
            this.tbl_OASYSCriteriaStandardScores = new HashSet<tbl_OASYSCriteriaStandardScores>();
            this.tbl_OASYSDistrictSettings = new HashSet<tbl_OASYSDistrictSettings>();
            this.tbl_OASYSEvaluationApprovals = new HashSet<tbl_OASYSEvaluationApprovals>();
            this.tbl_OASYSEvaluationApprovals1 = new HashSet<tbl_OASYSEvaluationApprovals>();
            this.tbl_OASYSEvaluationRights = new HashSet<tbl_OASYSEvaluationRights>();
            this.tbl_OASYSEvaluationRights1 = new HashSet<tbl_OASYSEvaluationRights>();
            this.tbl_OASYSEvidenceCriteria = new HashSet<tbl_OASYSEvidenceCriteria>();
            this.tbl_OASYSEvidenceCriteria1 = new HashSet<tbl_OASYSEvidenceCriteria>();
            this.tbl_OASYSEvidences = new HashSet<tbl_OASYSEvidences>();
            this.tbl_OASYSEvidences1 = new HashSet<tbl_OASYSEvidences>();
            this.tbl_OASYSImportTemplates = new HashSet<tbl_OASYSImportTemplates>();
            this.tbl_OASYSRubricCrtieriaScores = new HashSet<tbl_OASYSRubricCrtieriaScores>();
            this.tbl_OASYSScratchPad = new HashSet<tbl_OASYSScratchPad>();
            this.tbl_OASYSSectionScores = new HashSet<tbl_OASYSSectionScores>();
            this.tbl_OASYSSlos = new HashSet<tbl_OASYSSlos>();
            this.tbl_OASYSTeamExportLogEntries = new HashSet<tbl_OASYSTeamExportLogEntries>();
            this.tbl_OASYSTripodAnswers = new HashSet<tbl_OASYSTripodAnswers>();
            this.tbl_OASYSTripodCategoryRatings = new HashSet<tbl_OASYSTripodCategoryRatings>();
            this.tbl_OASYSUnalignedEvidences = new HashSet<tbl_OASYSUnalignedEvidences>();
            this.tbl_OASYSUnalignedEvidences1 = new HashSet<tbl_OASYSUnalignedEvidences>();
            this.tbl_OASYSUserComponentExceptions = new HashSet<tbl_OASYSUserComponentExceptions>();
            this.tbl_OASYSUserComponentInstances = new HashSet<tbl_OASYSUserComponentInstances>();
            this.tbl_OASYSUserComponents = new HashSet<tbl_OASYSUserComponents>();
            this.tbl_OASYSUserComponents1 = new HashSet<tbl_OASYSUserComponents>();
            this.tbl_OASYSUserFormComments = new HashSet<tbl_OASYSUserFormComments>();
            this.tbl_OASYSUserFormEvents = new HashSet<tbl_OASYSUserFormEvents>();
            this.tbl_OASYSUserForms = new HashSet<tbl_OASYSUserForms>();
            this.tbl_OASYSUserReports = new HashSet<tbl_OASYSUserReports>();
            this.tbl_OASYSUserShortcutes = new HashSet<tbl_OASYSUserShortcutes>();
            this.tbl_OASYSUserViewAdmins = new HashSet<tbl_OASYSUserViewAdmins>();
            this.tbl_OASYSUserViews = new HashSet<tbl_OASYSUserViews>();
            this.tbl_Prefs = new HashSet<tbl_Prefs>();
            this.tbl_ProgramAdmins = new HashSet<tbl_ProgramAdmins>();
            this.tbl_RegQuarterlyTransactions = new HashSet<tbl_RegQuarterlyTransactions>();
            this.tbl_RegTransactions = new HashSet<tbl_RegTransactions>();
            this.tbl_Reports = new HashSet<tbl_Reports>();
            this.tbl_ReportUsers = new HashSet<tbl_ReportUsers>();
            this.tbl_Rights = new HashSet<tbl_Rights>();
            this.tbl_SessionsActive = new HashSet<tbl_SessionsActive>();
            this.tbl_SessionsLog = new HashSet<tbl_SessionsLog>();
            this.tbl_StandardRecommendations = new HashSet<tbl_StandardRecommendations>();
            this.tbl_StandardRecommendations1 = new HashSet<tbl_StandardRecommendations>();
            this.tbl_StandardRecommendations2 = new HashSet<tbl_StandardRecommendations>();
            this.tbl_SupportActive = new HashSet<tbl_SupportActive>();
            this.tbl_SupportArchive = new HashSet<tbl_SupportArchive>();
            this.tbl_Surveys = new HashSet<tbl_Surveys>();
            this.tbl_TeamThreads = new HashSet<tbl_TeamThreads>();
            this.tbl_TeamTopics = new HashSet<tbl_TeamTopics>();
            this.tbl_UBuildings = new HashSet<tbl_UBuildings>();
            this.tbl_UCertifications = new HashSet<tbl_UCertifications>();
            this.tbl_UDegrees = new HashSet<tbl_UDegrees>();
            this.tbl_UDepartments = new HashSet<tbl_UDepartments>();
            this.tbl_UGrades = new HashSet<tbl_UGrades>();
            this.tbl_UMentors = new HashSet<tbl_UMentors>();
            this.tbl_UMentors1 = new HashSet<tbl_UMentors>();
            this.tbl_UPositionTypes = new HashSet<tbl_UPositionTypes>();
            this.tbl_UResumes = new HashSet<tbl_UResumes>();
            this.tbl_USalarySteps = new HashSet<tbl_USalarySteps>();
            this.tbl_UserPasswordReset = new HashSet<tbl_UserPasswordReset>();
            this.tbl_UserPersonAssociations = new HashSet<tbl_UserPersonAssociations>();
            this.tbl_UserViews = new HashSet<tbl_UserViews>();
            this.tbl_USignatures = new HashSet<tbl_USignatures>();
            this.tbl_WAComments = new HashSet<tbl_WAComments>();
            this.tbl_WAFiles = new HashSet<tbl_WAFiles>();
            this.tbl_WAURLs = new HashSet<tbl_WAURLs>();
            this.tbl_Webinars = new HashSet<tbl_Webinars>();
        }
    
        public int int_UserID { get; set; }
        public string var_FirstName { get; set; }
        public string var_LastName { get; set; }
        public string var_UserName { get; set; }
        public string var_Password { get; set; }
        public string var_SocialSecurityNum { get; set; }
        public string var_Email { get; set; }
        public int int_DistrictID { get; set; }
        public bool bit_EmailNotification { get; set; }
        public string var_JobTitle { get; set; }
        public Nullable<System.DateTime> dt_LastLoginDate { get; set; }
        public bool bit_IsInstructor { get; set; }
        public bool bit_IsSysAdmin { get; set; }
        public bool bit_IsDistrictAdmin { get; set; }
        public bool bit_IsDistrictConfig { get; set; }
        public bool bit_IsInstructional { get; set; }
        public bool bit_IsCatalogAdmin { get; set; }
        public Nullable<System.DateTime> dt_CertificateInitialDate { get; set; }
        public Nullable<System.DateTime> dt_CertificateExpirationDate { get; set; }
        public string var_CertificateArea { get; set; }
        public bool bit_Active { get; set; }
        public string var_SWStudentID { get; set; }
        public string var_SWPassword { get; set; }
        public string var_BuildingAssignment { get; set; }
        public string var_MLUserID { get; set; }
        public string var_MLPassword { get; set; }
        public bool bit_QuickApproveExisting { get; set; }
        public bool bit_QuickApproveNew { get; set; }
        public bool bit_EmailNewActivities { get; set; }
        public bool bit_EmailAdminNotification { get; set; }
        public bool bit_IsAccountingAdmin { get; set; }
        public bool bit_IsCustomerService { get; set; }
        public string var_BContact { get; set; }
        public string var_BAddress1 { get; set; }
        public string var_BAddress2 { get; set; }
        public string var_BCity { get; set; }
        public string var_BState { get; set; }
        public string var_BZip { get; set; }
        public string var_BPhone { get; set; }
        public string var_PaymentFormat { get; set; }
        public string var_CCNumber { get; set; }
        public int int_CCExpMonth { get; set; }
        public int int_CCExpYear { get; set; }
        public bool bit_IsMLP { get; set; }
        public bool bit_IsDemoUser { get; set; }
        public bool bit_EmailRemindEvents { get; set; }
        public string var_SignatureFileName { get; set; }
        public string var_EmployeeID { get; set; }
        public string var_BWorkPhone { get; set; }
        public int int_EMailRemindDays { get; set; }
        public int int_PositionTypeID { get; set; }
        public int int_Future3 { get; set; }
        public bool bit_IsProgramAdmin { get; set; }
        public System.DateTime dt_DateAdded { get; set; }
        public string var_PositionType { get; set; }
        public bool bit_IsEmailCustomer { get; set; }
        public bool bit_IsSubstitute { get; set; }
        public Nullable<System.DateTime> dt_DateHired { get; set; }
        public Nullable<System.DateTime> dt_DateTerminated { get; set; }
        public bool bit_IsBetaUser { get; set; }
        public string var_CalOptions { get; set; }
        public int int_CCCardCode { get; set; }
        public string var_CCFirstNameOnCard { get; set; }
        public string var_CCLastNameOnCard { get; set; }
        public bool bit_IsCalendarUser { get; set; }
        public bool bit_EMailHTMLBody { get; set; }
        public bool bit_CheckUserProfile { get; set; }
        public string var_BCountry { get; set; }
        public Nullable<System.DateTime> dt_DateOfBirth { get; set; }
        public string var_Gender { get; set; }
        public bool bit_ConfProposalSubmitted { get; set; }
        public bool bit_ConfRegistrationCompleted { get; set; }
        public bool bit_Voted { get; set; }
        public string var_WAddress1 { get; set; }
        public string var_WAddress2 { get; set; }
        public string var_WCity { get; set; }
        public string var_WZip { get; set; }
        public string var_WState { get; set; }
        public bool bit_PBSHasAccount { get; set; }
        public string var_PBSUserName { get; set; }
        public string var_CollegeInfo { get; set; }
        public bool bit_RequiresPhysicalAssistance { get; set; }
        public int int_SalaryStepID { get; set; }
        public string var_CertificateID { get; set; }
        public string var_LMSUserName { get; set; }
        public string var_IMSUserID { get; set; }
        public bool bit_IsHQT { get; set; }
        public string var_Email2 { get; set; }
        public string var_Email3 { get; set; }
        public Nullable<System.DateTime> dt_DateUpdated { get; set; }
        public string enc_SID { get; set; }
        public string enc_CCNumber { get; set; }
        public bool bit_StateUpload { get; set; }
        public Nullable<int> int_OASYSTypeID { get; set; }
        public Nullable<System.DateTime> dt_NextEvalDate { get; set; }
        public int int_TitleID { get; set; }
        public bool bit_EMailTeamRoom { get; set; }
        public string var_Race { get; set; }
        public Nullable<bool> bit_IsUSCitizen { get; set; }
        public Nullable<bool> bit_IsHispanic { get; set; }
        public string var_StateEmployeeId { get; set; }
        public Nullable<int> int_RoleId { get; set; }
        public string var_RemoteSysName { get; set; }
        public string var_RemoteSysID { get; set; }
        public Nullable<System.Guid> gd_PersonId { get; set; }
        public Nullable<System.Guid> gd_OrgPersonId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AInstructors> tbl_AInstructors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CalAdmins> tbl_CalAdmins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CalEntries> tbl_CalEntries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Comments> tbl_Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ConfPrefFeatures> tbl_ConfPrefFeatures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ConfRegistrations> tbl_ConfRegistrations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ConfSessionProposals> tbl_ConfSessionProposals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ConfSPropVotes> tbl_ConfSPropVotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DailyEmail> tbl_DailyEmail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DailyEMail_PRE> tbl_DailyEMail_PRE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Departments> tbl_Departments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DevelopmentRequests> tbl_DevelopmentRequests { get; set; }
        public virtual tbl_Districts tbl_Districts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_EmailOptions> tbl_EmailOptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_FundingUsers> tbl_FundingUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LearningPlan> tbl_LearningPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ListPrefs> tbl_ListPrefs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LogDetail> tbl_LogDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LPApprovals> tbl_LPApprovals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSAdHocReportActivity> tbl_OASYSAdHocReportActivity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSArchiveFormsRequest> tbl_OASYSArchiveFormsRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSArtifacts> tbl_OASYSArtifacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSComponentUserRights> tbl_OASYSComponentUserRights { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSCriteriaStandardScores> tbl_OASYSCriteriaStandardScores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSDistrictSettings> tbl_OASYSDistrictSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSEvaluationApprovals> tbl_OASYSEvaluationApprovals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSEvaluationApprovals> tbl_OASYSEvaluationApprovals1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSEvaluationRights> tbl_OASYSEvaluationRights { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSEvaluationRights> tbl_OASYSEvaluationRights1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSEvidenceCriteria> tbl_OASYSEvidenceCriteria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSEvidenceCriteria> tbl_OASYSEvidenceCriteria1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSEvidences> tbl_OASYSEvidences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSEvidences> tbl_OASYSEvidences1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSImportTemplates> tbl_OASYSImportTemplates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSRubricCrtieriaScores> tbl_OASYSRubricCrtieriaScores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSScratchPad> tbl_OASYSScratchPad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSSectionScores> tbl_OASYSSectionScores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSSlos> tbl_OASYSSlos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSTeamExportLogEntries> tbl_OASYSTeamExportLogEntries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSTripodAnswers> tbl_OASYSTripodAnswers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSTripodCategoryRatings> tbl_OASYSTripodCategoryRatings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSUnalignedEvidences> tbl_OASYSUnalignedEvidences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSUnalignedEvidences> tbl_OASYSUnalignedEvidences1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSUserComponentExceptions> tbl_OASYSUserComponentExceptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSUserComponentInstances> tbl_OASYSUserComponentInstances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSUserComponents> tbl_OASYSUserComponents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSUserComponents> tbl_OASYSUserComponents1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSUserFormComments> tbl_OASYSUserFormComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSUserFormEvents> tbl_OASYSUserFormEvents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSUserForms> tbl_OASYSUserForms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSUserReports> tbl_OASYSUserReports { get; set; }
        public virtual tbl_OASYSUserRights tbl_OASYSUserRights { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSUserShortcutes> tbl_OASYSUserShortcutes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSUserViewAdmins> tbl_OASYSUserViewAdmins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSUserViews> tbl_OASYSUserViews { get; set; }
        public virtual tbl_PositionTypes tbl_PositionTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Prefs> tbl_Prefs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ProgramAdmins> tbl_ProgramAdmins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_RegQuarterlyTransactions> tbl_RegQuarterlyTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_RegTransactions> tbl_RegTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Reports> tbl_Reports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ReportUsers> tbl_ReportUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Rights> tbl_Rights { get; set; }
        public virtual tbl_Roles tbl_Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SessionsActive> tbl_SessionsActive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SessionsLog> tbl_SessionsLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_StandardRecommendations> tbl_StandardRecommendations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_StandardRecommendations> tbl_StandardRecommendations1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_StandardRecommendations> tbl_StandardRecommendations2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SupportActive> tbl_SupportActive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SupportArchive> tbl_SupportArchive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Surveys> tbl_Surveys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TeamThreads> tbl_TeamThreads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TeamTopics> tbl_TeamTopics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_UBuildings> tbl_UBuildings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_UCertifications> tbl_UCertifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_UDegrees> tbl_UDegrees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_UDepartments> tbl_UDepartments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_UGrades> tbl_UGrades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_UMentors> tbl_UMentors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_UMentors> tbl_UMentors1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_UPositionTypes> tbl_UPositionTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_UResumes> tbl_UResumes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_USalarySteps> tbl_USalarySteps { get; set; }
        public virtual tbl_UserAuth tbl_UserAuth { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_UserPasswordReset> tbl_UserPasswordReset { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_UserPersonAssociations> tbl_UserPersonAssociations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_UserViews> tbl_UserViews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_USignatures> tbl_USignatures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_WAComments> tbl_WAComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_WAFiles> tbl_WAFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_WAURLs> tbl_WAURLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Webinars> tbl_Webinars { get; set; }
    }
}
