//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CatalogOptions
    {
        public int int_DistrictId { get; set; }
        public bool bit_SearchTerm { get; set; }
        public bool bit_SearchPurposes { get; set; }
        public bool bit_SearchGoals { get; set; }
        public bool bit_SearchStandards { get; set; }
        public bool bit_SearchInstructors { get; set; }
        public bool bit_SearchCategories { get; set; }
        public bool bit_SearchPrograms { get; set; }
        public bool bit_SearchLocations { get; set; }
        public bool bit_SearchActivityFormats { get; set; }
        public bool bit_SearchCourseCodes { get; set; }
        public bool bit_ShowInstructors { get; set; }
        public bool bit_ShowStandards { get; set; }
        public bool bit_ShowRegistrationFee { get; set; }
        public bool bit_ShowLocation { get; set; }
        public bool bit_ShowEnrollment { get; set; }
        public bool bit_ShowDescription { get; set; }
        public bool bit_ShowSearchDates { get; set; }
        public string var_SortBy { get; set; }
        public string var_SplashText { get; set; }
        public string var_EmptyText { get; set; }
    
        public virtual tbl_Districts tbl_Districts { get; set; }
    }
}
