//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Standards
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Standards()
        {
            this.tbl_AStandards = new HashSet<tbl_AStandards>();
            this.tbl_LPStandards = new HashSet<tbl_LPStandards>();
            this.tbl_OASYSCriteriaStandardScores = new HashSet<tbl_OASYSCriteriaStandardScores>();
            this.tbl_OASYSRubricCriteriaStandards = new HashSet<tbl_OASYSRubricCriteriaStandards>();
            this.tbl_StandardRecommendations = new HashSet<tbl_StandardRecommendations>();
        }
    
        public int int_StandardID { get; set; }
        public string var_Name { get; set; }
        public string var_Desc { get; set; }
        public string var_State { get; set; }
        public int int_Order { get; set; }
        public bool bit_Active { get; set; }
        public int int_DistrictID { get; set; }
        public int int_TeachingStandardID { get; set; }
        public string var_Code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AStandards> tbl_AStandards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LPStandards> tbl_LPStandards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSCriteriaStandardScores> tbl_OASYSCriteriaStandardScores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSRubricCriteriaStandards> tbl_OASYSRubricCriteriaStandards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_StandardRecommendations> tbl_StandardRecommendations { get; set; }
    }
}
