//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DistrictNews
    {
        public int int_DistrictNewsID { get; set; }
        public int int_DistrictID { get; set; }
        public System.DateTime dt_Date { get; set; }
        public System.DateTime dt_Expiration { get; set; }
        public string var_Title { get; set; }
        public string var_FullText { get; set; }
        public bool bit_AdminOnly { get; set; }
        public bool bit_Instructor { get; set; }
        public bool bit_ProgramAdmin { get; set; }
        public string var_News { get; set; }
    
        public virtual tbl_Districts tbl_Districts { get; set; }
    }
}
