//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Rights
    {
        public int int_RightsID { get; set; }
        public Nullable<int> int_UserID { get; set; }
        public int int_FormID { get; set; }
        public bool bit_View { get; set; }
        public bool bit_Save { get; set; }
        public bool bit_Design { get; set; }
        public Nullable<int> int_AdminRight { get; set; }
        public Nullable<int> int_RoleId { get; set; }
    
        public virtual tbl_UserProfile tbl_UserProfile { get; set; }
    }
}
