//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OASYSCriteriaStandardScores
    {
        public int int_UserID { get; set; }
        public int int_FormID { get; set; }
        public int int_EvaluationID { get; set; }
        public int int_InstanceID { get; set; }
        public int int_SectionID { get; set; }
        public int int_CriteriaID { get; set; }
        public int int_StandardID { get; set; }
        public int int_Threshold { get; set; }
        public Nullable<decimal> int_Score { get; set; }
        public System.DateTime dt_DateSubmitted { get; set; }
    
        public virtual tbl_OASYSEvaluations tbl_OASYSEvaluations { get; set; }
        public virtual tbl_OASYSForms tbl_OASYSForms { get; set; }
        public virtual tbl_OASYSRubricCriteria tbl_OASYSRubricCriteria { get; set; }
        public virtual tbl_OASYSSections tbl_OASYSSections { get; set; }
        public virtual tbl_Standards tbl_Standards { get; set; }
        public virtual tbl_UserProfile tbl_UserProfile { get; set; }
    }
}
