//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AExpenses
    {
        public int int_AExpenseID { get; set; }
        public int int_ActivityID { get; set; }
        public float rl_RegistrationFee { get; set; }
        public float rl_Transportation { get; set; }
        public float rl_Tolls { get; set; }
        public float rl_Meals { get; set; }
        public float rl_Lodging { get; set; }
        public float rl_OtherExpense1 { get; set; }
        public float rl_OtherExpense2 { get; set; }
        public float rl_OtherExpense3 { get; set; }
        public string var_OtherExpense1 { get; set; }
        public string var_OtherExpense2 { get; set; }
        public string var_OtherExpense3 { get; set; }
    
        public virtual tbl_Activities tbl_Activities { get; set; }
    }
}
