//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Buildings
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Buildings()
        {
            this.tbl_ABuildings = new HashSet<tbl_ABuildings>();
            this.tbl_BuildingGoals = new HashSet<tbl_BuildingGoals>();
            this.tbl_CalBuildings = new HashSet<tbl_CalBuildings>();
            this.tbl_LPBuildings = new HashSet<tbl_LPBuildings>();
            this.tbl_UBuildings = new HashSet<tbl_UBuildings>();
        }
    
        public int int_BuildingID { get; set; }
        public int int_DistrictID { get; set; }
        public string var_BuildingName { get; set; }
        public string var_BuildingType { get; set; }
        public string var_BuildingAddress2 { get; set; }
        public string var_BuildingAddress1 { get; set; }
        public string var_BuildingCity { get; set; }
        public string var_BuildingState { get; set; }
        public string var_BuildingZip { get; set; }
        public string var_BuildingContact { get; set; }
        public string var_BuildingPhone { get; set; }
        public int int_AdminID { get; set; }
        public int int_Order { get; set; }
        public int int_Admin2ID { get; set; }
        public string var_BuildingCode { get; set; }
        public int int_Admin3ID { get; set; }
        public bool bit_Active { get; set; }
        public int int_Admin4ID { get; set; }
        public int int_Admin5ID { get; set; }
        public string var_BNCESID { get; set; }
        public int int_Admin6ID { get; set; }
        public int int_Admin7ID { get; set; }
        public int int_Admin8ID { get; set; }
        public int int_Admin9ID { get; set; }
        public bool bit_IsExternal { get; set; }
        public string var_RemoteSysName { get; set; }
        public string var_RemoteSysID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ABuildings> tbl_ABuildings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_BuildingGoals> tbl_BuildingGoals { get; set; }
        public virtual tbl_Districts tbl_Districts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CalBuildings> tbl_CalBuildings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LPBuildings> tbl_LPBuildings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_UBuildings> tbl_UBuildings { get; set; }
    }
}
