//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OASYSUserReports
    {
        public int int_ReportID { get; set; }
        public int int_UserID { get; set; }
        public int int_ReportType { get; set; }
        public string nvar_ReportName { get; set; }
        public string nvar_Filter { get; set; }
        public string nvar_Options { get; set; }
        public bool bit_IsDeleted { get; set; }
        public bool bit_IsShared { get; set; }
        public System.DateTime dt_DateCreated { get; set; }
    
        public virtual tbl_UserProfile tbl_UserProfile { get; set; }
    }
}
