//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UResumes
    {
        public int int_UResumeID { get; set; }
        public string var_ContactName { get; set; }
        public string var_JobTitle { get; set; }
        public string var_Employer { get; set; }
        public string var_ContactAddress { get; set; }
        public string var_ContactCity { get; set; }
        public string var_ContactState { get; set; }
        public string var_ContactZip { get; set; }
        public string var_ContactPhoneW { get; set; }
        public string var_ContactPhoneH { get; set; }
        public string var_ContactPhoneM { get; set; }
        public string var_URLImage { get; set; }
        public string var_URLWebsite { get; set; }
        public string var_URLFacebook { get; set; }
        public string var_ContractType { get; set; }
        public string var_ContractRate { get; set; }
        public Nullable<System.DateTime> dt_ContractStartDate { get; set; }
        public Nullable<System.DateTime> dt_ContractEndDate { get; set; }
        public string var_Resume { get; set; }
        public string var_OtherText01 { get; set; }
        public string var_OtherText02 { get; set; }
        public string var_OtherText03 { get; set; }
        public string var_OtherLargeText01 { get; set; }
        public string var_OtherLargeText02 { get; set; }
        public string var_OtherLargeText03 { get; set; }
        public bool bit_ShowAddress { get; set; }
        public bool bit_ShowEmail { get; set; }
        public bool bit_ShowPhoneW { get; set; }
        public bool bit_ShowPhoneH { get; set; }
        public bool bit_ShowPhoneM { get; set; }
        public bool bit_ShowEmployer { get; set; }
        public bool bit_ShowJobTitle { get; set; }
        public bool bit_ShowPicture { get; set; }
        public bool bit_ShowOtherText01 { get; set; }
        public bool bit_ShowOtherText02 { get; set; }
        public bool bit_ShowOtherText03 { get; set; }
        public bool bit_ShowOtherLargeText01 { get; set; }
        public bool bit_ShowOtherLargeText02 { get; set; }
        public bool bit_ShowOtherLargeText03 { get; set; }
        public bool bit_Active { get; set; }
        public int int_UserID { get; set; }
        public int int_FileID { get; set; }
    
        public virtual tbl_Files tbl_Files { get; set; }
        public virtual tbl_UserProfile tbl_UserProfile { get; set; }
    }
}
