//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OASYSSections
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_OASYSSections()
        {
            this.tbl_OASYSCompositeScoreCriteria = new HashSet<tbl_OASYSCompositeScoreCriteria>();
            this.tbl_OASYSCriteriaStandardScores = new HashSet<tbl_OASYSCriteriaStandardScores>();
            this.tbl_OASYSImportTemplateSections = new HashSet<tbl_OASYSImportTemplateSections>();
            this.tbl_OASYSRubricCrtieriaScores = new HashSet<tbl_OASYSRubricCrtieriaScores>();
            this.tbl_OASYSSectionScores = new HashSet<tbl_OASYSSectionScores>();
        }
    
        public int int_SectionID { get; set; }
        public bool bit_IsAdminOnly { get; set; }
        public bool bit_IsConfigOnly { get; set; }
        public bool bit_IsDelete { get; set; }
        public bool bit_IsProtected { get; set; }
        public bool bit_IsPublic { get; set; }
        public bool bit_IsReadOnly { get; set; }
        public bool bit_IsRequired { get; set; }
        public bool bit_UseNote { get; set; }
        public bool bit_UseSpellCheck { get; set; }
        public int int_FormID { get; set; }
        public Nullable<int> int_RepeatFormID { get; set; }
        public Nullable<int> int_RepeatSubFormID { get; set; }
        public int int_Size { get; set; }
        public string nvar_Config { get; set; }
        public string nvar_DefaultValue { get; set; }
        public string nvar_ExtraFieldName { get; set; }
        public string nvar_FieldName { get; set; }
        public string nvar_FieldValues { get; set; }
        public string nvar_Name { get; set; }
        public string nvar_SortField { get; set; }
        public string nvar_SubType { get; set; }
        public string nvar_Type { get; set; }
        public short sint_DisplayOrder { get; set; }
        public Nullable<short> sint_Lines { get; set; }
        public Nullable<short> sint_Width { get; set; }
        public string var_ColumnType { get; set; }
        public Nullable<int> int_ReferenceKey { get; set; }
        public string nvar_ExportKey { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSCompositeScoreCriteria> tbl_OASYSCompositeScoreCriteria { get; set; }
        public virtual tbl_OASYSCompositeScoreSections tbl_OASYSCompositeScoreSections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSCriteriaStandardScores> tbl_OASYSCriteriaStandardScores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSImportTemplateSections> tbl_OASYSImportTemplateSections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSRubricCrtieriaScores> tbl_OASYSRubricCrtieriaScores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSSectionScores> tbl_OASYSSectionScores { get; set; }
    }
}
