//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OtherFields
    {
        public int int_OtherFieldID { get; set; }
        public string var_TableName { get; set; }
        public int int_ID { get; set; }
        public string var_OtherField1 { get; set; }
        public string var_OtherField2 { get; set; }
        public string var_OtherField3 { get; set; }
        public string var_OtherField4 { get; set; }
        public string var_OtherField5 { get; set; }
        public string var_OtherField6 { get; set; }
        public string var_OtherField7 { get; set; }
        public string var_OtherField8 { get; set; }
        public string var_OtherField9 { get; set; }
        public string var_OtherField10 { get; set; }
        public string var_OtherField11 { get; set; }
        public string var_OtherField12 { get; set; }
        public string var_OtherField13 { get; set; }
        public string var_OtherField14 { get; set; }
        public string var_OtherField15 { get; set; }
        public string var_OtherField16 { get; set; }
        public string var_OtherField17 { get; set; }
        public string var_OtherField18 { get; set; }
        public string var_OtherField19 { get; set; }
        public string var_OtherField20 { get; set; }
        public string var_OtherField21 { get; set; }
        public string var_OtherField22 { get; set; }
        public string var_OtherField23 { get; set; }
        public string var_OtherField24 { get; set; }
        public string var_OtherField25 { get; set; }
        public string var_OtherField26 { get; set; }
        public string var_OtherField27 { get; set; }
        public string var_OtherField28 { get; set; }
        public string var_OtherField29 { get; set; }
        public string var_OtherField30 { get; set; }
        public string var_OtherField31 { get; set; }
        public string var_OtherField32 { get; set; }
        public string var_OtherField33 { get; set; }
        public string var_OtherField34 { get; set; }
        public string var_OtherField35 { get; set; }
        public string var_OtherField36 { get; set; }
        public string var_OtherField37 { get; set; }
        public string var_OtherField38 { get; set; }
        public string var_OtherField39 { get; set; }
        public string var_OtherField40 { get; set; }
        public string var_OtherField41 { get; set; }
        public string var_OtherField42 { get; set; }
        public string var_OtherField43 { get; set; }
        public string var_OtherField44 { get; set; }
        public string var_OtherField45 { get; set; }
        public string var_OtherField46 { get; set; }
        public string var_OtherField47 { get; set; }
        public string var_OtherField48 { get; set; }
        public string var_OtherField49 { get; set; }
        public string var_OtherField50 { get; set; }
        public string var_OtherField51 { get; set; }
        public string var_OtherField52 { get; set; }
        public string var_OtherField53 { get; set; }
        public string var_OtherField54 { get; set; }
        public string var_OtherField55 { get; set; }
        public string var_OtherField56 { get; set; }
        public string var_OtherField57 { get; set; }
        public string var_OtherField58 { get; set; }
        public string var_OtherField59 { get; set; }
        public string var_OtherField60 { get; set; }
        public string var_OtherField61 { get; set; }
        public string var_OtherField62 { get; set; }
        public string var_OtherField63 { get; set; }
        public string var_OtherField64 { get; set; }
        public string var_OtherField65 { get; set; }
        public string var_OtherField66 { get; set; }
        public string var_OtherField67 { get; set; }
        public string var_OtherField68 { get; set; }
        public string var_OtherField69 { get; set; }
        public string var_OtherField70 { get; set; }
        public string var_OtherField71 { get; set; }
        public string var_OtherField72 { get; set; }
        public string var_OtherField73 { get; set; }
        public string var_OtherField74 { get; set; }
        public string var_OtherField75 { get; set; }
        public string var_OtherField76 { get; set; }
        public string var_OtherField77 { get; set; }
        public string var_OtherField78 { get; set; }
        public string var_OtherField79 { get; set; }
        public string var_OtherField80 { get; set; }
        public string var_OtherField81 { get; set; }
        public string var_OtherField82 { get; set; }
        public string var_OtherField83 { get; set; }
        public string var_OtherField84 { get; set; }
        public string var_OtherField85 { get; set; }
        public string var_OtherField86 { get; set; }
        public string var_OtherField87 { get; set; }
        public string var_OtherField88 { get; set; }
        public string var_OtherField89 { get; set; }
        public string var_OtherField90 { get; set; }
        public string var_OtherField91 { get; set; }
        public string var_OtherField92 { get; set; }
        public string var_OtherField93 { get; set; }
        public string var_OtherField94 { get; set; }
        public string var_OtherField95 { get; set; }
        public string var_OtherField96 { get; set; }
        public string var_OtherField97 { get; set; }
        public string var_OtherField98 { get; set; }
        public string var_OtherField99 { get; set; }
        public string var_OtherField100 { get; set; }
        public Nullable<System.DateTime> dt_LastUpdated { get; set; }
    }
}
