//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PaymentFormats
    {
        public int int_PaymentFormatID { get; set; }
        public Nullable<int> int_DistrictID { get; set; }
        public string var_Name { get; set; }
        public string var_Description { get; set; }
        public Nullable<int> int_Order { get; set; }
        public bool bit_Active { get; set; }
    
        public virtual tbl_Districts tbl_Districts { get; set; }
    }
}
