//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OASYSUserViews
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_OASYSUserViews()
        {
            this.tbl_OASYSUserViewAdmins = new HashSet<tbl_OASYSUserViewAdmins>();
        }
    
        public int int_ViewID { get; set; }
        public int int_UserID { get; set; }
        public string nvar_ColumnModel { get; set; }
        public string nvar_Filter { get; set; }
        public bool bit_IsDefault { get; set; }
        public int int_PageNumber { get; set; }
        public int int_PageSize { get; set; }
        public string nvar_SortColumn { get; set; }
        public string nvar_SortDir { get; set; }
        public string nvar_ViewName { get; set; }
        public bool bit_IsShared { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSUserViewAdmins> tbl_OASYSUserViewAdmins { get; set; }
        public virtual tbl_UserProfile tbl_UserProfile { get; set; }
    }
}
