//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FormElements
    {
        public int Int_FormElementID { get; set; }
        public int int_FormID { get; set; }
        public int int_Order { get; set; }
        public string var_FieldName { get; set; }
        public string var_Type { get; set; }
        public string var_Text { get; set; }
        public string var_Value { get; set; }
        public bool bit_IsRequired { get; set; }
        public bool bit_IsNumeric { get; set; }
        public int int_Width { get; set; }
        public int int_Height { get; set; }
        public int int_Lines { get; set; }
        public string var_HelpMessage { get; set; }
        public bool bit_IsSystemForm { get; set; }
        public bool bit_DisplayAsLink { get; set; }
        public bool bit_DistrictAdminOnly { get; set; }
        public bool bit_UserCanEdit { get; set; }
        public bool bit_DistrictConfigOnly { get; set; }
        public string var_DefaultValue { get; set; }
        public string var_SQL { get; set; }
    
        public virtual tbl_Forms tbl_Forms { get; set; }
    }
}
