//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LPFundings
    {
        public int int_LPFundingID { get; set; }
        public Nullable<int> int_LearningPlanID { get; set; }
        public Nullable<int> int_FundingSourceID { get; set; }
        public Nullable<decimal> mon_Amount { get; set; }
        public Nullable<int> int_AdminID { get; set; }
        public string var_BudgetYear { get; set; }
    
        public virtual tbl_FundingSources tbl_FundingSources { get; set; }
        public virtual tbl_LearningPlan tbl_LearningPlan { get; set; }
    }
}
