//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LPObjectives
    {
        public int int_LPObjectiveID { get; set; }
        public Nullable<int> int_LearningPlanID { get; set; }
        public Nullable<int> int_ObjectiveID { get; set; }
    
        public virtual tbl_LearningPlan tbl_LearningPlan { get; set; }
        public virtual tbl_Objectives tbl_Objectives { get; set; }
    }
}
