//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ConfSPropMLPFeatures
    {
        public int int_SPropMLPFeatureID { get; set; }
        public int int_ConfSessionProposalID { get; set; }
        public int int_MLPFeatureID { get; set; }
    }
}
