//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Plans
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Plans()
        {
            this.tbl_PlanObjectives = new HashSet<tbl_PlanObjectives>();
        }
    
        public int int_PlanID { get; set; }
        public string var_PlanTitle { get; set; }
        public string var_PlanDesc { get; set; }
        public Nullable<System.DateTime> dt_StartDate { get; set; }
        public Nullable<System.DateTime> dt_EndDate { get; set; }
        public string txt_NeedsAssessment { get; set; }
        public string txt_BaselineDesc { get; set; }
        public string txt_Goals { get; set; }
        public string txt_KnowledgeAssessment { get; set; }
        public string txt_ApplicationAssessment { get; set; }
        public string txt_ImpactAssessment { get; set; }
        public int int_AdminID { get; set; }
        public System.DateTime dt_SubmissionDate { get; set; }
        public int int_DistrictID { get; set; }
        public bool bit_Active { get; set; }
        public int int_Order { get; set; }
        public string txt_OutCome { get; set; }
        public string txt_Reflection { get; set; }
        public string txt_Comments { get; set; }
        public int int_FileID { get; set; }
        public string txt_SMARTStudent { get; set; }
        public string txt_ImpactOverall { get; set; }
        public string txt_ReflectionFuture { get; set; }
        public bool bit_ReflectionGoalsMet { get; set; }
        public string txt_KnowledgeData { get; set; }
        public string var_KForms { get; set; }
        public string var_KEvals { get; set; }
        public string var_KSurveys { get; set; }
        public string var_AForms { get; set; }
        public string var_AEvals { get; set; }
        public string var_ASurveys { get; set; }
        public string var_IForms { get; set; }
        public string var_IEvals { get; set; }
        public string var_ISurveys { get; set; }
        public bool bit_UseTeamrooms { get; set; }
        public string var_KLogForms { get; set; }
        public string var_ALogForms { get; set; }
        public string txt_ApplicationData { get; set; }
        public string txt_ResultsData { get; set; }
        public string var_GoalStatus { get; set; }
    
        public virtual tbl_Districts tbl_Districts { get; set; }
        public virtual tbl_Files tbl_Files { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PlanObjectives> tbl_PlanObjectives { get; set; }
    }
}
