//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OASYSEvidenceCriteria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_OASYSEvidenceCriteria()
        {
            this.tbl_OASYSEvidences = new HashSet<tbl_OASYSEvidences>();
        }
    
        public int int_EvidenceCriteriaID { get; set; }
        public int int_SectionID { get; set; }
        public int int_CriteriaID { get; set; }
        public int int_FormID { get; set; }
        public int int_UserID { get; set; }
        public int int_InstanceID { get; set; }
        public int int_EvaluationID { get; set; }
        public System.DateTime dt_DateCreated { get; set; }
        public int int_AdminID { get; set; }
        public Nullable<int> int_RubricLevelID { get; set; }
        public Nullable<System.DateTime> dt_DateScored { get; set; }
        public Nullable<int> int_ScoreAdminID { get; set; }
    
        public virtual tbl_OASYSEvaluations tbl_OASYSEvaluations { get; set; }
        public virtual tbl_OASYSForms tbl_OASYSForms { get; set; }
        public virtual tbl_OASYSRubricCriteria tbl_OASYSRubricCriteria { get; set; }
        public virtual tbl_UserProfile tbl_UserProfile { get; set; }
        public virtual tbl_UserProfile tbl_UserProfile1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSEvidences> tbl_OASYSEvidences { get; set; }
    }
}
