//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EnrollmentStatus
    {
        public int int_EnrollmentStatusID { get; set; }
        public string chr_EnrollmentStatus { get; set; }
        public string var_EnrollmentStatus { get; set; }
        public string var_AdminDesc { get; set; }
        public string var_Desc { get; set; }
        public int int_Order { get; set; }
        public bool bit_Active { get; set; }
    }
}
