//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OASYSCompositeScoreCriteria
    {
        public int int_CriterionID { get; set; }
        public int int_CompositeScoreSectionID { get; set; }
        public int int_CriterionSectionID { get; set; }
        public decimal dec_Weight { get; set; }
        public string nvar_Name { get; set; }
        public bool bit_Optional { get; set; }
        public Nullable<int> int_WeightSectionID { get; set; }
        public Nullable<int> int_OptionalSectionID { get; set; }
        public string nvar_OptionalMatchValue { get; set; }
    
        public virtual tbl_OASYSCompositeScoreSections tbl_OASYSCompositeScoreSections { get; set; }
        public virtual tbl_OASYSSections tbl_OASYSSections { get; set; }
    }
}
