//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OASYSTripodCategories
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_OASYSTripodCategories()
        {
            this.tbl_OASYSTripodCategoryRatings = new HashSet<tbl_OASYSTripodCategoryRatings>();
            this.tbl_OASYSTripodQuestions = new HashSet<tbl_OASYSTripodQuestions>();
        }
    
        public int int_CategoryID { get; set; }
        public int int_DistrictID { get; set; }
        public int int_GroupID { get; set; }
        public System.DateTime dt_DateCreated { get; set; }
        public string nvar_Name { get; set; }
        public string nvar_Goal { get; set; }
        public string nvar_Description { get; set; }
    
        public virtual tbl_Districts tbl_Districts { get; set; }
        public virtual tbl_OASYSTripodGroups tbl_OASYSTripodGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSTripodCategoryRatings> tbl_OASYSTripodCategoryRatings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSTripodQuestions> tbl_OASYSTripodQuestions { get; set; }
    }
}
