//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UCertifications
    {
        public int int_UCertificationID { get; set; }
        public Nullable<int> int_UserID { get; set; }
        public string var_Type { get; set; }
        public string var_Area { get; set; }
        public Nullable<System.DateTime> dt_IssueDate { get; set; }
        public string var_Status { get; set; }
        public System.DateTime dt_LastUpdate { get; set; }
        public System.DateTime dt_ExpirationDate { get; set; }
        public bool bit_ManualAddEdit { get; set; }
        public string var_Code { get; set; }
        public string var_EndorsementCode { get; set; }
    
        public virtual tbl_UserProfile tbl_UserProfile { get; set; }
    }
}
