//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Help
    {
        public int int_HelpID { get; set; }
        public string var_HelpTitle { get; set; }
        public string var_HelpDescription { get; set; }
        public string var_HelpSteps { get; set; }
        public string var_Role { get; set; }
        public int int_Order { get; set; }
    }
}
