//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SessionsLog
    {
        public int int_SessionLogID { get; set; }
        public int int_UserID { get; set; }
        public System.DateTime dt_StartTime { get; set; }
        public Nullable<int> int_PageCount { get; set; }
        public Nullable<int> int_Minutes { get; set; }
        public string var_UserAgent { get; set; }
        public string var_Host { get; set; }
        public int int_WebRegID { get; set; }
    
        public virtual tbl_UserProfile tbl_UserProfile { get; set; }
    }
}
