//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_RegPPaymentTypes
    {
        public int int_RegPPaymentTypeID { get; set; }
        public int int_ProgramID { get; set; }
        public int int_RegPaymentTypeID { get; set; }
    
        public virtual tbl_Programs tbl_Programs { get; set; }
        public virtual tbl_RegPaymentTypes tbl_RegPaymentTypes { get; set; }
    }
}
