//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OASYSUserForms
    {
        public int int_EvaluationID { get; set; }
        public int int_FormID { get; set; }
        public int int_UserID { get; set; }
        public Nullable<int> int_ScheduledFor { get; set; }
        public Nullable<int> int_ScheduledBy { get; set; }
        public Nullable<int> int_ApprovedBy { get; set; }
        public Nullable<System.DateTime> dt_ScheduledDate { get; set; }
        public string nvar_ScheduledPlace { get; set; }
        public bool bit_IsCompleted { get; set; }
        public bool bit_IsApproved { get; set; }
        public bool bit_IsAcknowledged { get; set; }
        public int int_Duration { get; set; }
        public string nvar_Notes { get; set; }
        public Nullable<System.DateTime> dt_CompletedDate { get; set; }
        public bool bit_IsScheduleAcknowledged { get; set; }
        public int int_ComponentID { get; set; }
        public Nullable<int> int_AdminID { get; set; }
        public Nullable<int> int_SubmittedBy { get; set; }
        public Nullable<System.DateTime> dt_AcknowledgedDate { get; set; }
        public int int_InstanceID { get; set; }
        public string nvar_ComponentTitle { get; set; }
        public bool bit_InFinal { get; set; }
        public bool bit_ShowInEvalProfile { get; set; }
        public bool bit_RequiresAcknowledgment { get; set; }
        public bool bit_Active { get; set; }
        public Nullable<System.DateTime> dt_LastSaved { get; set; }
        public Nullable<System.DateTime> dt_StartDate { get; set; }
        public Nullable<System.DateTime> dt_EndDate { get; set; }
        public Nullable<System.DateTime> dt_DateFinalized { get; set; }
        public bool bit_NotifyUser { get; set; }
        public Nullable<System.DateTime> dt_DueDate { get; set; }
        public bool bit_IsReSubmitted { get; set; }
        public Nullable<System.DateTime> dt_DateReSubmitted { get; set; }
        public bool bit_RequireReSubmit { get; set; }
        public bool bit_IsAcknowledgedInPastCycle { get; set; }
    
        public virtual tbl_OASYSEvaluations tbl_OASYSEvaluations { get; set; }
        public virtual tbl_OASYSForms tbl_OASYSForms { get; set; }
        public virtual tbl_OASYSSlos tbl_OASYSSlos { get; set; }
        public virtual tbl_UserProfile tbl_UserProfile { get; set; }
    }
}
