//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DOEDistricts
    {
        public string var_DistrictName { get; set; }
        public string var_CountyName { get; set; }
        public string var_Address { get; set; }
        public string var_City { get; set; }
        public string var_State { get; set; }
        public string var_Zip { get; set; }
        public string var_Zip4 { get; set; }
        public string var_Phone { get; set; }
        public int int_SugarDID { get; set; }
        public Nullable<int> int_MLPDID { get; set; }
        public Nullable<int> int_HawkDID { get; set; }
        public string var_DNCESID { get; set; }
        public string var_StateID { get; set; }
        public Nullable<double> rl_StudentsNum { get; set; }
        public Nullable<double> rl_TeachersNum { get; set; }
        public Nullable<double> rl_SchoolsNum { get; set; }
        public string NewLocaleCode { get; set; }
        public string NewLocaleShortDesc { get; set; }
        public Nullable<double> StudentTeach_Ratio { get; set; }
        public string Migrant { get; set; }
        public string var_Type { get; set; }
        public string var_MSC { get; set; }
        public int int_DOEDistrictID { get; set; }
    }
}
