//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CLicensesIndividual
    {
        public int int_CLicensesIndividualID { get; set; }
        public int int_UserID { get; set; }
        public int int_CCatalogID { get; set; }
        public System.DateTime dt_StartDate { get; set; }
        public System.DateTime dt_EndDate { get; set; }
        public string var_PaymentInfo { get; set; }
        public int int_PassingScore { get; set; }
    
        public virtual tbl_CCatalog tbl_CCatalog { get; set; }
    }
}
