//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OASYSTripodAnswers
    {
        public int int_AnswerID { get; set; }
        public int int_UserID { get; set; }
        public int int_QuestionID { get; set; }
        public string nvar_Year { get; set; }
        public int int_Season { get; set; }
        public Nullable<byte> int_Score { get; set; }
        public string nvar_Subject { get; set; }
    
        public virtual tbl_OASYSTripodQuestions tbl_OASYSTripodQuestions { get; set; }
        public virtual tbl_UserProfile tbl_UserProfile { get; set; }
    }
}
