//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UserViews
    {
        public int int_ViewID { get; set; }
        public int int_UserID { get; set; }
        public string nvar_ViewPage { get; set; }
        public string nvar_ColumnModel { get; set; }
        public string nvar_Filter { get; set; }
        public bool bit_IsDefault { get; set; }
        public int int_PageNumber { get; set; }
        public int int_PageSize { get; set; }
        public string nvar_SortColumn { get; set; }
        public string nvar_SortDir { get; set; }
        public string nvar_ViewName { get; set; }
        public bool bit_IsShared { get; set; }
    
        public virtual tbl_UserProfile tbl_UserProfile { get; set; }
    }
}
