//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SalarySteps
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_SalarySteps()
        {
            this.tbl_LPSalarySteps = new HashSet<tbl_LPSalarySteps>();
            this.tbl_USalarySteps = new HashSet<tbl_USalarySteps>();
        }
    
        public int int_SalaryStepID { get; set; }
        public int int_DistrictID { get; set; }
        public string var_SalaryStepName { get; set; }
        public int int_Order { get; set; }
        public bool bit_Active { get; set; }
        public string var_SalaryStepDesc { get; set; }
        public string var_StepCode { get; set; }
    
        public virtual tbl_Districts tbl_Districts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LPSalarySteps> tbl_LPSalarySteps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_USalarySteps> tbl_USalarySteps { get; set; }
    }
}
