//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ReportFields
    {
        public int int_ReportFieldID { get; set; }
        public string var_TableName { get; set; }
        public string var_TableDisplayName { get; set; }
        public string var_FieldName { get; set; }
        public string var_FieldDisplayName { get; set; }
        public string var_Type { get; set; }
        public int int_Width { get; set; }
        public bool bit_SubTotal { get; set; }
        public bool bit_Count { get; set; }
        public bool bit_SysAdminOnly { get; set; }
        public bool bit_MLP { get; set; }
        public bool bit_WebReg { get; set; }
        public int int_HTMLWidth { get; set; }
        public bool bit_ContentCustomer { get; set; }
    }
}
