//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OASYSTeamExportLogEntries
    {
        public int int_ID { get; set; }
        public int int_DistrictID { get; set; }
        public string var_Message { get; set; }
        public System.DateTime dt_TimeStamp { get; set; }
        public Nullable<int> int_UserID { get; set; }
        public Nullable<int> int_BuildingID { get; set; }
        public string var_ObservationFormName { get; set; }
        public bool bit_IsError { get; set; }
        public bool bit_IsSuccess { get; set; }
    
        public virtual tbl_Districts tbl_Districts { get; set; }
        public virtual tbl_UserProfile tbl_UserProfile { get; set; }
    }
}
