//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LPExpenses
    {
        public int int_LPExpenseID { get; set; }
        public int int_LearningplanID { get; set; }
        public float rl_RRegistrationFee { get; set; }
        public float rl_RTransportation { get; set; }
        public float rl_RTolls { get; set; }
        public float rl_RMeals { get; set; }
        public float rl_RLodging { get; set; }
        public float rl_ROtherExpense1 { get; set; }
        public float rl_ROtherExpense2 { get; set; }
        public float rl_ROtherExpense3 { get; set; }
        public float rl_ARegistrationFee { get; set; }
        public float rl_ATransportation { get; set; }
        public float rl_ATolls { get; set; }
        public float rl_AMeals { get; set; }
        public float rl_ALodging { get; set; }
        public float rl_AOtherExpense1 { get; set; }
        public float rl_AOtherExpense2 { get; set; }
        public float rl_AOtherExpense3 { get; set; }
        public float rl_FRegistrationFee { get; set; }
        public float rl_FTransportation { get; set; }
        public float rl_FTolls { get; set; }
        public float rl_FMeals { get; set; }
        public float rl_FLodging { get; set; }
        public float rl_FOtherExpense1 { get; set; }
        public float rl_FOtherExpense2 { get; set; }
        public float rl_FOtherExpense3 { get; set; }
        public string var_OtherExpense1 { get; set; }
        public string var_OtherExpense2 { get; set; }
        public string var_OtherExpense3 { get; set; }
    
        public virtual tbl_LearningPlan tbl_LearningPlan { get; set; }
    }
}
