//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DRenewalLog
    {
        public int int_DRenewalID { get; set; }
        public int int_DistrictID { get; set; }
        public Nullable<System.DateTime> dt_DateRenewalCall { get; set; }
        public int int_AlertLevel { get; set; }
        public string var_MLPContactName { get; set; }
        public string var_Comments { get; set; }
        public int int_UserID { get; set; }
        public System.DateTime dt_SubmissionDate { get; set; }
    
        public virtual tbl_Districts tbl_Districts { get; set; }
    }
}
