//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_HowTo
    {
        public int int_HowToID { get; set; }
        public string var_HowToTitle { get; set; }
        public string var_HowToMoreInfo { get; set; }
        public string var_SpecialInstructions { get; set; }
        public string var_ScreenCamPath { get; set; }
        public Nullable<bool> bit_AdminOnly { get; set; }
        public string var_type { get; set; }
        public string var_category { get; set; }
        public Nullable<bool> bit_Active { get; set; }
        public Nullable<int> int_Order { get; set; }
        public Nullable<System.DateTime> dt_DateAdded { get; set; }
        public Nullable<System.DateTime> dt_LastUpdated { get; set; }
    }
}
