//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LogDetail
    {
        public int int_LogDetailID { get; set; }
        public int int_UserID { get; set; }
        public int int_DistrictID { get; set; }
        public string var_Host { get; set; }
        public string var_Resource { get; set; }
        public string var_Params { get; set; }
        public string var_Cookie { get; set; }
        public Nullable<System.DateTime> dt_Date { get; set; }
        public string var_Machine { get; set; }
        public int int_Instance { get; set; }
    
        public virtual tbl_Districts tbl_Districts { get; set; }
        public virtual tbl_UserProfile tbl_UserProfile { get; set; }
    }
}
