//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ConfSessionProposals
    {
        public int int_ConfSessionProposalID { get; set; }
        public int int_UserID { get; set; }
        public string var_Title { get; set; }
        public string var_Description { get; set; }
        public string var_CoPresenter1 { get; set; }
        public string var_CoPresenter1District { get; set; }
        public string var_CoPresenter2 { get; set; }
        public string var_CoPresenter2District { get; set; }
        public string var_CoPresenter3 { get; set; }
        public string var_CoPresenter3District { get; set; }
        public bool bit_Active { get; set; }
        public int int_Years { get; set; }
        public int int_Focus { get; set; }
        public int int_Target { get; set; }
    
        public virtual tbl_UserProfile tbl_UserProfile { get; set; }
    }
}
