//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SessionsActive
    {
        public int int_SessionsActiveID { get; set; }
        public System.Guid GUID { get; set; }
        public Nullable<int> int_UserID { get; set; }
        public Nullable<System.DateTime> dt_StartTime { get; set; }
        public Nullable<System.DateTime> dt_LastAccess { get; set; }
        public Nullable<int> int_PageCount { get; set; }
        public Nullable<int> int_DistrictID { get; set; }
        public Nullable<int> int_SubjectID { get; set; }
        public string var_DistrictState { get; set; }
        public string var_DistrictName { get; set; }
        public string var_FirstName { get; set; }
        public string var_LastName { get; set; }
        public string var_Email { get; set; }
        public string var_Grade { get; set; }
        public Nullable<bool> bit_IsDistrictAdmin { get; set; }
        public bool bit_IsDistrictConfig { get; set; }
        public Nullable<bool> bit_IsInstructor { get; set; }
        public bool bit_IsCatalogAdmin { get; set; }
        public bool bit_IsAccountingAdmin { get; set; }
        public bool bit_IsCustomerService { get; set; }
        public Nullable<bool> bit_IsSysAdmin { get; set; }
        public Nullable<bool> bit_IsInstructional { get; set; }
        public string var_UserAgent { get; set; }
        public string var_Host { get; set; }
        public string var_SelectedTab { get; set; }
        public bool bit_IsMLP { get; set; }
        public int int_WebRegID { get; set; }
        public bool bit_ChangePassword { get; set; }
        public bool bit_ChangeUserName { get; set; }
        public bool bit_IsProgramAdmin { get; set; }
        public string var_WebRegDistrictName { get; set; }
        public string var_WebRegLogoFile { get; set; }
        public string var_WebRegReturnURL { get; set; }
        public string var_WebRegHeaderColor { get; set; }
        public string var_WebRegLeftNavColor { get; set; }
        public bool bit_WebRegIsRegCustomer { get; set; }
        public bool bit_WebRegUseHeader { get; set; }
        public bool bit_IsEmailCustomer { get; set; }
        public string var_GMTOffset { get; set; }
        public bool bit_IsWebHostCustomer { get; set; }
        public bool bit_UseWorkflow { get; set; }
        public bool bit_WebRegMulti { get; set; }
        public bool bit_IsBetaUser { get; set; }
        public int int_SessionTimeoutMin { get; set; }
        public bool bit_IsFileUploadCustomer { get; set; }
        public bool bit_IsFileUploadUsers { get; set; }
        public bool bit_IsCalendarCustomer { get; set; }
        public bool bit_IsCalendarUser { get; set; }
        public bool bit_ConfProposalSubmitted { get; set; }
        public bool bit_ConfRegistrationCompleted { get; set; }
        public bool bit_Voted { get; set; }
        public string txt_Prefs { get; set; }
        public string var_Rights { get; set; }
        public string var_AbsenceProviderName { get; set; }
        public bool bit_IsDistrictOasysCustomer { get; set; }
        public bool bit_IsDistrictMLPCustomer { get; set; }
        public bool bit_IsDistrictElevateCustomer { get; set; }
        public bool bit_IsDistrictNISCustomer { get; set; }
        public bool bit_IsDistrictFormHogCustomer { get; set; }
        public bool bit_IsDistrictETSvideoCustomer { get; set; }
        public int int_OasysTypeId { get; set; }
        public Nullable<System.DateTime> dt_NextEvalDate { get; set; }
        public short sint_OasysRights { get; set; }
        public bool bit_IsOasysDistrictAdmin { get; set; }
        public bool bit_IsOasysDistrictConfig { get; set; }
        public string var_LDAPConfig { get; set; }
        public string var_SAMLConfig { get; set; }
        public string var_SupportContact { get; set; }
        public string var_ExecContact { get; set; }
        public string var_ScratchPad { get; set; }
        public bool bit_IsContentCustomer { get; set; }
        public bool bit_IsMyVideoCustomer { get; set; }
        public bool bit_IsVideoChannelCustomer { get; set; }
        public bool bit_IsSubstitute { get; set; }
        public bool bit_IsDistrictIDMEnabled { get; set; }
        public int int_FLOrgID { get; set; }
        public bool bit_IsGlobalDirectoryEnabled { get; set; }
    
        public virtual tbl_Districts tbl_Districts { get; set; }
        public virtual tbl_UserProfile tbl_UserProfile { get; set; }
    }
}
