//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_HelpImages
    {
        public int int_HelpImageID { get; set; }
        public string var_ImageTitle { get; set; }
        public string var_ImageDescription { get; set; }
        public int int_ImageSize { get; set; }
        public System.DateTime dt_DateUploaded { get; set; }
        public string var_Category { get; set; }
        public byte[] bin_ImageData { get; set; }
        public byte[] bin_ImageThumb { get; set; }
        public string var_Role { get; set; }
    }
}
