//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FormTemplateData
    {
        public int int_FormTemplateDataID { get; set; }
        public int int_FormTemplateID { get; set; }
        public string var_FieldName { get; set; }
        public string var_FieldValue { get; set; }
    
        public virtual tbl_FormTemplates tbl_FormTemplates { get; set; }
    }
}
