//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OASYSImportTemplateSections
    {
        public int int_ImportTemplateID { get; set; }
        public int int_SectionID { get; set; }
        public int int_Index { get; set; }
    
        public virtual tbl_OASYSImportTemplates tbl_OASYSImportTemplates { get; set; }
        public virtual tbl_OASYSSections tbl_OASYSSections { get; set; }
    }
}
