//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OASYSRubrics
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_OASYSRubrics()
        {
            this.tbl_OASYSRubricCriteria = new HashSet<tbl_OASYSRubricCriteria>();
            this.tbl_OASYSRubricLevels = new HashSet<tbl_OASYSRubricLevels>();
        }
    
        public int int_RubricID { get; set; }
        public string nvar_RubricName { get; set; }
        public int int_DistrictID { get; set; }
        public bool bit_IsDeleted { get; set; }
        public bool bit_ShowNotes { get; set; }
        public bool bit_showOnlySelected { get; set; }
        public bool bit_showCriteria { get; set; }
        public bool bit_IsScored { get; set; }
        public bool bit_AlignToStandards { get; set; }
        public bool bit_ShowSelectedLevel { get; set; }
        public bool bit_ExcludeArtifactAlignment { get; set; }
        public string nvar_Code { get; set; }
        public string nvar_CriteriaTitle { get; set; }
    
        public virtual tbl_Districts tbl_Districts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSRubricCriteria> tbl_OASYSRubricCriteria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSRubricLevels> tbl_OASYSRubricLevels { get; set; }
    }
}
