//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ConfPrefFeatures
    {
        public int int_ConfPrefFeatureID { get; set; }
        public int int_UserID { get; set; }
        public bool bit_Feature1 { get; set; }
        public bool bit_Feature2 { get; set; }
        public bool bit_Feature3 { get; set; }
        public bool bit_Feature4 { get; set; }
        public bool bit_Feature5 { get; set; }
        public bool bit_Feature6 { get; set; }
        public bool bit_Feature7 { get; set; }
        public bool bit_Feature8 { get; set; }
        public bool bit_Feature9 { get; set; }
        public bool bit_Feature10 { get; set; }
        public bool bit_Feature11 { get; set; }
        public bool bit_Feature12 { get; set; }
        public bool bit_Feature13 { get; set; }
        public bool bit_Feature14 { get; set; }
        public bool bit_Feature15 { get; set; }
        public bool bit_Feature16 { get; set; }
        public bool bit_Feature17 { get; set; }
        public bool bit_Feature18 { get; set; }
        public bool bit_Feature19 { get; set; }
        public bool bit_Feature20 { get; set; }
    
        public virtual tbl_UserProfile tbl_UserProfile { get; set; }
    }
}
