//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FDLogs
    {
        public long int_FDLogId { get; set; }
        public Nullable<System.DateTime> dt_LastRun { get; set; }
        public Nullable<bool> bit_Success { get; set; }
    }
}
