//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Webinars
    {
        public int int_WebinarID { get; set; }
        public string var_Title { get; set; }
        public string var_Description { get; set; }
        public string var_URL { get; set; }
        public bool bit_MLP { get; set; }
        public bool bit_WebReg { get; set; }
        public bool bit_Active { get; set; }
        public Nullable<System.DateTime> dt_Date { get; set; }
        public string var_Time { get; set; }
        public int int_DistrictID { get; set; }
        public int int_UserID { get; set; }
        public string var_Type { get; set; }
        public string var_Instructions { get; set; }
        public string var_Sponsor { get; set; }
        public bool bit_OASYS { get; set; }
        public string var_ShareURL { get; set; }
        public string var_EmbedURL { get; set; }
        public string var_DownloadURL { get; set; }
    
        public virtual tbl_UserProfile tbl_UserProfile { get; set; }
    }
}
