//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PDEReferenceStatus
    {
        public int int_PDEReferenceID { get; set; }
        public int int_PDEReference { get; set; }
        public string var_PDEReferenceTitle { get; set; }
        public string var_PDEReferenceDesc { get; set; }
        public string var_PDEReferenceHelp { get; set; }
        public int int_Order { get; set; }
        public string var_Category { get; set; }
    }
}
