//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DRegionalProviders
    {
        public int int_DRegionalProviderID { get; set; }
        public int int_DistrictID { get; set; }
        public int int_ProviderID { get; set; }
        public int int_FormID { get; set; }
        public string var_Title { get; set; }
        public string var_Notes { get; set; }
        public bool bit_DisplayOnLeftNav { get; set; }
        public int int_Order { get; set; }
        public bool bit_AllowMarketing { get; set; }
        public string var_Type { get; set; }
        public bool bit_CopyOtherFields { get; set; }
    
        public virtual tbl_Districts tbl_Districts { get; set; }
        public virtual tbl_Providers tbl_Providers { get; set; }
    }
}
