//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UBuildings
    {
        public int int_UBuildingID { get; set; }
        public Nullable<int> int_UserID { get; set; }
        public Nullable<int> int_BuildingID { get; set; }
        public bool bit_IsPrimary { get; set; }
    
        public virtual tbl_Buildings tbl_Buildings { get; set; }
        public virtual tbl_UserProfile tbl_UserProfile { get; set; }
    }
}
