//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DOEBuildings
    {
        public int ID { get; set; }
        public string var_BNCESID { get; set; }
        public string var_DNCESID { get; set; }
        public string var_DistrictName { get; set; }
        public string var_BuildingName { get; set; }
        public string var_BuildingCity { get; set; }
        public string var_BuildingState { get; set; }
        public Nullable<double> int_MetroLocalID { get; set; }
        public Nullable<double> int_UrbanLocalID { get; set; }
        public Nullable<double> int_SchoolStatusID { get; set; }
        public int int_DOEBuildingID { get; set; }
    }
}
