//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LPSalarySteps
    {
        public int int_LPSalaryStepID { get; set; }
        public int int_LearningPlanID { get; set; }
        public int int_SalaryStepID { get; set; }
        public float rl_HoursUsed { get; set; }
        public float rl_CreditsUsed { get; set; }
        public int int_AdminID { get; set; }
        public Nullable<System.DateTime> dt_DateApproved { get; set; }
        public bool bit_Split { get; set; }
        public Nullable<System.DateTime> dt_DateSubmitted { get; set; }
    
        public virtual tbl_LearningPlan tbl_LearningPlan { get; set; }
        public virtual tbl_SalarySteps tbl_SalarySteps { get; set; }
    }
}
