//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OASYSTripodCategoryRatings
    {
        public int int_CategoryRatingID { get; set; }
        public int int_UserID { get; set; }
        public int int_CategoryID { get; set; }
        public string nvar_Year { get; set; }
        public int int_Season { get; set; }
        public decimal dec_Rating { get; set; }
    
        public virtual tbl_OASYSTripodCategories tbl_OASYSTripodCategories { get; set; }
        public virtual tbl_UserProfile tbl_UserProfile { get; set; }
    }
}
