//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_HowToElements
    {
        public int int_HowToElementID { get; set; }
        public int int_HowToID { get; set; }
        public int int_HowToOrder { get; set; }
        public int int_HowToStepID { get; set; }
    }
}
