//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_HowToSteps
    {
        public int int_HowToStepID { get; set; }
        public string var_StepTitle { get; set; }
        public string var_StepMoreInfo { get; set; }
        public string var_Path { get; set; }
        public string var_ScreenCam { get; set; }
        public string var_category { get; set; }
    }
}
