//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SamlServiceProviderConfigs
    {
        public int int_Id { get; set; }
        public string var_Name { get; set; }
        public string var_ConsumerServiceUrl { get; set; }
        public int int_MapTo { get; set; }
        public int int_ClaimType { get; set; }
        public bool bit_Sign { get; set; }
    }
}
