//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_HowToEval
    {
        public int int_HowToEvalID { get; set; }
        public int int_HowToID { get; set; }
        public bool bit_WasHelpful { get; set; }
        public Nullable<int> int_HowToRating { get; set; }
    }
}
