//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CBundles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_CBundles()
        {
            this.tbl_CSessions = new HashSet<tbl_CSessions>();
        }
    
        public int int_CBundleID { get; set; }
        public int int_CCatalogID { get; set; }
        public string var_Title { get; set; }
        public string var_Desc { get; set; }
        public string var_Objectives { get; set; }
        public string var_Topics { get; set; }
        public string var_Features { get; set; }
        public string var_Prerequsites { get; set; }
        public string var_Trademarks { get; set; }
        public string var_ProductCode { get; set; }
        public float rl_Hours { get; set; }
        public float rl_Credits { get; set; }
        public int int_Order { get; set; }
    
        public virtual tbl_CCatalog tbl_CCatalog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CSessions> tbl_CSessions { get; set; }
    }
}
