//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OASYSComponentUserRights
    {
        public int int_UserID { get; set; }
        public int int_ComponentID { get; set; }
        public int int_AdminUserId { get; set; }
        public int int_Rights { get; set; }
    
        public virtual tbl_OASYSComponents tbl_OASYSComponents { get; set; }
        public virtual tbl_UserProfile tbl_UserProfile { get; set; }
    }
}
