//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_USalarySteps
    {
        public int int_USalaryStepID { get; set; }
        public int int_UserID { get; set; }
        public int int_SalaryStepID { get; set; }
        public System.DateTime dt_SubmissionDate { get; set; }
        public string var_Status { get; set; }
        public string var_Comments { get; set; }
        public string var_AdminComments { get; set; }
        public bool bit_Archived { get; set; }
        public string var_ReviewComments { get; set; }
    
        public virtual tbl_SalarySteps tbl_SalarySteps { get; set; }
        public virtual tbl_UserProfile tbl_UserProfile { get; set; }
    }
}
