//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Calendars
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Calendars()
        {
            this.tbl_CalAdmins = new HashSet<tbl_CalAdmins>();
            this.tbl_CalBuildings = new HashSet<tbl_CalBuildings>();
            this.tbl_CalDepartments = new HashSet<tbl_CalDepartments>();
            this.tbl_CalEntries = new HashSet<tbl_CalEntries>();
            this.tbl_CalGrades = new HashSet<tbl_CalGrades>();
            this.tbl_CalGroups = new HashSet<tbl_CalGroups>();
        }
    
        public int int_CalendarID { get; set; }
        public int int_DistrictID { get; set; }
        public string var_Name { get; set; }
        public string var_ShortName { get; set; }
        public string var_Code { get; set; }
        public string var_TextColor { get; set; }
        public bool bit_PublicView { get; set; }
        public bool bit_Archived { get; set; }
        public int int_Order { get; set; }
        public int int_ColorCodeID { get; set; }
        public bool bit_ShowExternal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CalAdmins> tbl_CalAdmins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CalBuildings> tbl_CalBuildings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CalDepartments> tbl_CalDepartments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CalEntries> tbl_CalEntries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CalGrades> tbl_CalGrades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CalGroups> tbl_CalGroups { get; set; }
    }
}
