//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OASYSRiScoreExtractPanelConfig
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_OASYSRiScoreExtractPanelConfig()
        {
            this.tbl_OASYSRiScoreExtractFieldConfig = new HashSet<tbl_OASYSRiScoreExtractFieldConfig>();
        }
    
        public int int_ID { get; set; }
        public int int_ConfigID { get; set; }
        public string nvar_PanelId { get; set; }
        public string nvar_EvalTypeBoxId { get; set; }
        public string nvar_EvalTypeBoxValue { get; set; }
    
        public virtual tbl_OASYSRiScoreExtractConfig tbl_OASYSRiScoreExtractConfig { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSRiScoreExtractFieldConfig> tbl_OASYSRiScoreExtractFieldConfig { get; set; }
    }
}
