//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MLPContacts
    {
        public int int_MLPContactID { get; set; }
        public string var_FirstName { get; set; }
        public string var_LastName { get; set; }
        public string var_DistrictName { get; set; }
        public string var_Address { get; set; }
        public string var_OrgType { get; set; }
        public int int_FTE { get; set; }
        public string var_Phone { get; set; }
        public string var_Email { get; set; }
        public System.DateTime dt_DateStamp { get; set; }
        public string var_Source { get; set; }
        public string var_SourceInfo { get; set; }
        public bool bit_CallForDemo { get; set; }
        public string var_BestTime { get; set; }
        public bool bit_SendProposal { get; set; }
        public string var_Note { get; set; }
        public string var_TitlePosition { get; set; }
        public string var_ProductName { get; set; }
    }
}
