//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SupportNotes
    {
        public int int_SupportNoteID { get; set; }
        public string var_FirstName { get; set; }
        public string var_Note { get; set; }
        public System.DateTime dt_StartViewing { get; set; }
        public Nullable<System.DateTime> dt_EndViewing { get; set; }
        public bool bit_Elizabeth { get; set; }
        public bool bit_Jennifer { get; set; }
        public bool bit_Mike { get; set; }
        public bool bit_Robert { get; set; }
        public bool bit_Maureen { get; set; }
        public bool bit_Frank { get; set; }
        public bool bit_Betty { get; set; }
        public bool bit_Lisa { get; set; }
        public bool bit_Tom { get; set; }
    }
}
