//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ZipCodes
    {
        public int int_ZipCodesID { get; set; }
        public string var_ZipCode { get; set; }
        public string var_City { get; set; }
        public string var_State { get; set; }
        public Nullable<float> rl_Lat { get; set; }
        public Nullable<float> rl_Lon { get; set; }
    }
}
