//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_HostSubSectionContent
    {
        public int int_HostSubSectionContentID { get; set; }
        public string var_Type { get; set; }
        public int int_SectionID { get; set; }
        public int int_Order { get; set; }
        public string var_Option1 { get; set; }
        public string var_Option2 { get; set; }
        public string var_Option3 { get; set; }
        public string var_Option4 { get; set; }
        public string var_Option5 { get; set; }
        public string var_Option6 { get; set; }
        public string var_Option7 { get; set; }
        public string var_Option8 { get; set; }
        public string var_Option9 { get; set; }
        public string var_Option10 { get; set; }
        public string Content { get; set; }
    }
}
