//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FileAttachments
    {
        public int int_FileAttachmentID { get; set; }
        public int int_FileID { get; set; }
        public string var_TableName { get; set; }
        public int int_ID { get; set; }
    }
}
