//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ActivityFormats
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_ActivityFormats()
        {
            this.tbl_LPBank = new HashSet<tbl_LPBank>();
        }
    
        public int int_ActivityFormatID { get; set; }
        public int int_DistrictID { get; set; }
        public string var_ActivityFormatDesc { get; set; }
        public int int_Order { get; set; }
        public string var_ShortName { get; set; }
        public bool bit_Active { get; set; }
        public string var_Code { get; set; }
        public bool bit_Bankable { get; set; }
    
        public virtual tbl_Districts tbl_Districts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LPBank> tbl_LPBank { get; set; }
    }
}
