//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LearningPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_LearningPlan()
        {
            this.tbl_CSessions = new HashSet<tbl_CSessions>();
            this.tbl_LPApprovals = new HashSet<tbl_LPApprovals>();
            this.tbl_LPBank = new HashSet<tbl_LPBank>();
            this.tbl_LPBuildingGoals = new HashSet<tbl_LPBuildingGoals>();
            this.tbl_LPBuildings = new HashSet<tbl_LPBuildings>();
            this.tbl_LPCategories = new HashSet<tbl_LPCategories>();
            this.tbl_LPCertificates = new HashSet<tbl_LPCertificates>();
            this.tbl_LPContent = new HashSet<tbl_LPContent>();
            this.tbl_LPDepartments = new HashSet<tbl_LPDepartments>();
            this.tbl_LPDistricts = new HashSet<tbl_LPDistricts>();
            this.tbl_LPEvalMethods = new HashSet<tbl_LPEvalMethods>();
            this.tbl_LPExpenses = new HashSet<tbl_LPExpenses>();
            this.tbl_LPFollowUps = new HashSet<tbl_LPFollowUps>();
            this.tbl_LPFundings = new HashSet<tbl_LPFundings>();
            this.tbl_LPGrades = new HashSet<tbl_LPGrades>();
            this.tbl_LPGroups = new HashSet<tbl_LPGroups>();
            this.tbl_LPInstructors = new HashSet<tbl_LPInstructors>();
            this.tbl_LPLocations = new HashSet<tbl_LPLocations>();
            this.tbl_LPLogs = new HashSet<tbl_LPLogs>();
            this.tbl_LPMeetingDates = new HashSet<tbl_LPMeetingDates>();
            this.tbl_LPObjectives = new HashSet<tbl_LPObjectives>();
            this.tbl_LPPlans = new HashSet<tbl_LPPlans>();
            this.tbl_LPPreRequisites = new HashSet<tbl_LPPreRequisites>();
            this.tbl_LPPromoCodes = new HashSet<tbl_LPPromoCodes>();
            this.tbl_LPPurposes = new HashSet<tbl_LPPurposes>();
            this.tbl_LPRegOptions = new HashSet<tbl_LPRegOptions>();
            this.tbl_LPSalarySteps = new HashSet<tbl_LPSalarySteps>();
            this.tbl_LPStandards = new HashSet<tbl_LPStandards>();
            this.tbl_LPSubs = new HashSet<tbl_LPSubs>();
            this.tbl_LPUsers = new HashSet<tbl_LPUsers>();
        }
    
        public int int_LearningPlanID { get; set; }
        public int int_DistrictID { get; set; }
        public int int_ActivityID { get; set; }
        public int int_UserID { get; set; }
        public int int_PaymentFormatID { get; set; }
        public int int_CCatalogID { get; set; }
        public int int_EventID { get; set; }
        public string var_Type { get; set; }
        public Nullable<System.DateTime> dt_SubmissionDate { get; set; }
        public Nullable<System.DateTime> dt_StartDate { get; set; }
        public string var_ActivityTitle { get; set; }
        public string var_ActivityDesc { get; set; }
        public string var_URL { get; set; }
        public float rl_ActivityHours { get; set; }
        public float rl_Credits { get; set; }
        public bool bit_ApprovalRequired { get; set; }
        public int int_ApprovalStatus { get; set; }
        public bool bit_Reapproval { get; set; }
        public Nullable<System.DateTime> dt_DateExpired { get; set; }
        public float rl_HoursAttended { get; set; }
        public int int_InstructorUserID { get; set; }
        public string var_InstructorName { get; set; }
        public Nullable<System.DateTime> dt_DateCompleted { get; set; }
        public string var_MeetingDates { get; set; }
        public Nullable<int> int_FormID { get; set; }
        public int int_ActivityFormatID { get; set; }
        public int int_ProviderID { get; set; }
        public string var_ProviderName { get; set; }
        public Nullable<System.DateTime> dt_EndDate { get; set; }
        public bool bit_SubRequired { get; set; }
        public string var_SubRequested { get; set; }
        public string var_Comments { get; set; }
        public int int_PDEReference { get; set; }
        public bool bit_PDEResubmit { get; set; }
        public string var_ConferenceLocation { get; set; }
        public string var_SolutionWhereID { get; set; }
        public bool bit_EmailTeacher { get; set; }
        public bool bit_Future1 { get; set; }
        public bool bit_Future2 { get; set; }
        public bool bit_Future3 { get; set; }
        public string chr_WebRegStatus { get; set; }
        public string var_SessionCode { get; set; }
        public string var_Future3 { get; set; }
        public float rl_Future3 { get; set; }
        public int int_MinUsers { get; set; }
        public int int_WaitListMax { get; set; }
        public int int_CourseCodeID { get; set; }
        public int int_RegOptionID { get; set; }
        public int int_RegPaymentID { get; set; }
        public bool bit_IsActivityProposal { get; set; }
        public bool bit_Archived { get; set; }
        public int int_MaxUsers { get; set; }
        public string var_CourseCode { get; set; }
        public bool bit_UserCanEdit { get; set; }
        public float rl_RExpenses { get; set; }
        public float rl_AExpenses { get; set; }
        public float rl_FExpenses { get; set; }
        public int int_RegCourseGradeID { get; set; }
        public string chr_EnrollmentStatus { get; set; }
        public Nullable<System.DateTime> dt_StartShowing { get; set; }
        public Nullable<System.DateTime> dt_StopShowing { get; set; }
        public string var_SubConfirmationID { get; set; }
        public bool bit_Recommended { get; set; }
        public string var_DescriptionLarge { get; set; }
        public int int_EvalFormID { get; set; }
        public Nullable<bool> bit_TeamRoomDiscussEnabled { get; set; }
        public Nullable<bool> bit_TeamRoomFilesEnabled { get; set; }
        public string var_Audience { get; set; }
        public Nullable<int> int_ProgramID { get; set; }
        public string var_Annotations { get; set; }
        public Nullable<int> int_OwnerID { get; set; }
        public Nullable<System.DateTime> dt_LastUpdated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CSessions> tbl_CSessions { get; set; }
        public virtual tbl_Districts tbl_Districts { get; set; }
        public virtual tbl_Forms tbl_Forms { get; set; }
        public virtual tbl_UserProfile tbl_UserProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LPApprovals> tbl_LPApprovals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LPBank> tbl_LPBank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LPBuildingGoals> tbl_LPBuildingGoals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LPBuildings> tbl_LPBuildings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LPCategories> tbl_LPCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LPCertificates> tbl_LPCertificates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LPContent> tbl_LPContent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LPDepartments> tbl_LPDepartments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LPDistricts> tbl_LPDistricts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LPEvalMethods> tbl_LPEvalMethods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LPExpenses> tbl_LPExpenses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LPFollowUps> tbl_LPFollowUps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LPFundings> tbl_LPFundings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LPGrades> tbl_LPGrades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LPGroups> tbl_LPGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LPInstructors> tbl_LPInstructors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LPLocations> tbl_LPLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LPLogs> tbl_LPLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LPMeetingDates> tbl_LPMeetingDates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LPObjectives> tbl_LPObjectives { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LPPlans> tbl_LPPlans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LPPreRequisites> tbl_LPPreRequisites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LPPromoCodes> tbl_LPPromoCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LPPurposes> tbl_LPPurposes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LPRegOptions> tbl_LPRegOptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LPSalarySteps> tbl_LPSalarySteps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LPStandards> tbl_LPStandards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LPSubs> tbl_LPSubs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LPUsers> tbl_LPUsers { get; set; }
    }
}
