//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UserAuth
    {
        public int int_UserId { get; set; }
        public bool bit_IsCaseSensitive { get; set; }
        public byte[] vbin_Token { get; set; }
        public Nullable<System.DateTime> dt_Expiration { get; set; }
        public System.DateTime dt_Modified { get; set; }
        public System.DateTime dt_Created { get; set; }
    
        public virtual tbl_UserProfile tbl_UserProfile { get; set; }
    }
}
