//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CPromos
    {
        public int int_CPromoID { get; set; }
        public Nullable<System.DateTime> dt_StartDate { get; set; }
        public Nullable<System.DateTime> dt_EndDate { get; set; }
        public string var_Title { get; set; }
        public string var_FullText { get; set; }
        public string var_URL { get; set; }
    }
}
