//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OASYSSlos
    {
        public int int_FormID { get; set; }
        public int int_UserID { get; set; }
        public int int_EvaluationID { get; set; }
        public int int_InstanceID { get; set; }
        public Nullable<int> int_ConversionSheetID { get; set; }
        public Nullable<decimal> dec_BaselineScore { get; set; }
        public Nullable<decimal> dec_FinalScore { get; set; }
        public Nullable<decimal> dec_AggregateScore { get; set; }
        public string nvar_CourseID { get; set; }
        public string nvar_Name { get; set; }
        public string nvar_TargetStatement { get; set; }
        public Nullable<int> int_NumberOfStudentsStart { get; set; }
        public Nullable<int> int_NumberOfStudentsEnd { get; set; }
        public string nvar_Assessment { get; set; }
        public Nullable<decimal> dec_AggregateTarget { get; set; }
        public string nvar_TargetGrade { get; set; }
        public string nvar_TargetContentArea { get; set; }
        public Nullable<decimal> dec_HediScore { get; set; }
        public string nvar_HediRating { get; set; }
    
        public virtual tbl_OASYSConversionSheets tbl_OASYSConversionSheets { get; set; }
        public virtual tbl_OASYSEvaluations tbl_OASYSEvaluations { get; set; }
        public virtual tbl_OASYSForms tbl_OASYSForms { get; set; }
        public virtual tbl_OASYSUserForms tbl_OASYSUserForms { get; set; }
        public virtual tbl_UserProfile tbl_UserProfile { get; set; }
    }
}
