//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OASYSComponentTemplateForms
    {
        public int int_ComponentID { get; set; }
        public int int_FormID { get; set; }
        public int int_Index { get; set; }
    
        public virtual tbl_OASYSComponentTemplates tbl_OASYSComponentTemplates { get; set; }
        public virtual tbl_OASYSForms tbl_OASYSForms { get; set; }
    }
}
