//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TeamForms
    {
        public int int_TeamFormID { get; set; }
        public int int_ActivityID { get; set; }
        public int int_FormID { get; set; }
        public string var_LinkTitle { get; set; }
        public string var_LinkDesc { get; set; }
        public string var_URL { get; set; }
        public string var_LinkInstructions { get; set; }
        public Nullable<System.DateTime> dt_StartShowing { get; set; }
        public Nullable<System.DateTime> dt_StopShowing { get; set; }
        public bool bit_ResultsToInstructor { get; set; }
        public bool bit_ResultsToUsers { get; set; }
        public bool bit_InstructorOnly { get; set; }
        public bool bit_Active { get; set; }
        public int int_Order { get; set; }
        public bool bit_IsReflection { get; set; }
    }
}
