//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BuildingGoals
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_BuildingGoals()
        {
            this.tbl_LPBuildingGoals = new HashSet<tbl_LPBuildingGoals>();
        }
    
        public int int_BuildingGoalID { get; set; }
        public int int_BuildingID { get; set; }
        public string var_BuildingGoalName { get; set; }
        public string var_BuildingGoalDesc { get; set; }
        public int int_Order { get; set; }
        public bool bit_Active { get; set; }
    
        public virtual tbl_Buildings tbl_Buildings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LPBuildingGoals> tbl_LPBuildingGoals { get; set; }
    }
}
