//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FundingSources
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_FundingSources()
        {
            this.tbl_FundingUsers = new HashSet<tbl_FundingUsers>();
            this.tbl_LPFundings = new HashSet<tbl_LPFundings>();
        }
    
        public int int_FundingSourceID { get; set; }
        public int int_DistrictID { get; set; }
        public string var_Name { get; set; }
        public string var_BudgetCode { get; set; }
        public decimal mon_BudgetAmount { get; set; }
        public int int_Order { get; set; }
        public bool bit_Active { get; set; }
        public bool bit_SendToAbsenceProvider { get; set; }
    
        public virtual tbl_Districts tbl_Districts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_FundingUsers> tbl_FundingUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LPFundings> tbl_LPFundings { get; set; }
    }
}
