//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_IPToDomain
    {
        public int int_IPToDomainID { get; set; }
        public string var_Host { get; set; }
        public string var_DomainName { get; set; }
        public string var_BlockOwner { get; set; }
        public string var_City { get; set; }
        public string var_State { get; set; }
        public string var_Type { get; set; }
    }
}
