//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FormRules
    {
        public int int_FormRuleID { get; set; }
        public int int_FormID { get; set; }
        public string var_FieldName { get; set; }
        public string var_Operator { get; set; }
        public string var_Value { get; set; }
        public string var_ActionType { get; set; }
        public string var_ActionValue { get; set; }
        public int int_Order { get; set; }
        public string var_eMailTo { get; set; }
    
        public virtual tbl_Forms tbl_Forms { get; set; }
    }
}
