//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DevelopmentRequests
    {
        public int int_DevID { get; set; }
        public string var_DevRequest { get; set; }
        public string var_Description { get; set; }
        public System.DateTime dt_SubmissionDate { get; set; }
        public string var_RequestType { get; set; }
        public string var_Priority { get; set; }
        public string var_Complexity { get; set; }
        public bool bit_Complete { get; set; }
        public Nullable<System.DateTime> dt_CompletedDate { get; set; }
        public string var_Developer { get; set; }
        public string var_DeveloperNotes { get; set; }
        public string var_Page { get; set; }
        public string var_CodeSource { get; set; }
        public int int_UserID { get; set; }
    
        public virtual tbl_UserProfile tbl_UserProfile { get; set; }
    }
}
