//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OASYSTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_OASYSTypes()
        {
            this.tbl_OASYSComponents = new HashSet<tbl_OASYSComponents>();
            this.tbl_OASYSEvaluationApprovals = new HashSet<tbl_OASYSEvaluationApprovals>();
            this.tbl_OASYSNyScoreExtractCriteria = new HashSet<tbl_OASYSNyScoreExtractCriteria>();
            this.tbl_OASYSArtifactGroups = new HashSet<tbl_OASYSArtifactGroups>();
        }
    
        public int int_TypeID { get; set; }
        public string nvar_TypeTitle { get; set; }
        public int int_DistrictID { get; set; }
        public Nullable<int> int_RubricID { get; set; }
        public bool bit_IsActive { get; set; }
        public string nvar_Description { get; set; }
        public Nullable<int> int_NextEvaluationTypeId { get; set; }
        public Nullable<System.DateTime> date_DefaultStartDate { get; set; }
        public Nullable<int> int_DefaultDuration { get; set; }
        public Nullable<int> int_EmployeeClassificationID { get; set; }
        public string nvar_ExportKey { get; set; }
    
        public virtual tbl_Districts tbl_Districts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSComponents> tbl_OASYSComponents { get; set; }
        public virtual tbl_OASYSEmployeeClassifications tbl_OASYSEmployeeClassifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSEvaluationApprovals> tbl_OASYSEvaluationApprovals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSNyScoreExtractCriteria> tbl_OASYSNyScoreExtractCriteria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSArtifactGroups> tbl_OASYSArtifactGroups { get; set; }
    }
}
