//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Groups
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Groups()
        {
            this.tbl_CalGroups = new HashSet<tbl_CalGroups>();
            this.tbl_GroupUsers = new HashSet<tbl_GroupUsers>();
            this.tbl_LPGroups = new HashSet<tbl_LPGroups>();
        }
    
        public int int_GroupID { get; set; }
        public int int_DistrictID { get; set; }
        public string var_Name { get; set; }
        public string var_Description { get; set; }
        public bool bit_Archived { get; set; }
        public string var_GroupCode { get; set; }
        public int int_Order { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CalGroups> tbl_CalGroups { get; set; }
        public virtual tbl_Districts tbl_Districts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_GroupUsers> tbl_GroupUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LPGroups> tbl_LPGroups { get; set; }
    }
}
