//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LPContent
    {
        public int int_LPContentID { get; set; }
        public int int_LearningPlanID { get; set; }
        public int int_ContentID { get; set; }
        public Nullable<System.DateTime> dt_LastAccessed { get; set; }
        public string var_Bookmark { get; set; }
        public string var_Status { get; set; }
        public float rl_Score { get; set; }
        public string var_Time { get; set; }
        public string var_Grade { get; set; }
        public string var_LMSLastRequest { get; set; }
    
        public virtual tbl_Content tbl_Content { get; set; }
        public virtual tbl_LearningPlan tbl_LearningPlan { get; set; }
    }
}
