//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_RegPaymentTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_RegPaymentTypes()
        {
            this.tbl_RegPPaymentTypes = new HashSet<tbl_RegPPaymentTypes>();
        }
    
        public int int_RegPaymentTypeID { get; set; }
        public string var_Name { get; set; }
        public string var_Description { get; set; }
        public string var_Units { get; set; }
        public bool bit_ApprovalRequired { get; set; }
        public bool bit_MembershipRequired { get; set; }
        public bool bit_MC { get; set; }
        public bool bit_Visa { get; set; }
        public bool bit_Amex { get; set; }
        public bool bit_Discover { get; set; }
        public bool bit_DinersClub { get; set; }
        public bool bit_DebitCard { get; set; }
        public string var_ShortName { get; set; }
        public bool bit_DistrictPays { get; set; }
        public bool bit_AdminOnly { get; set; }
        public bool bit_Active { get; set; }
        public bool bit_CCVerifyAddress { get; set; }
        public bool bit_CCVerifyCCV { get; set; }
        public bool bit_ECheck { get; set; }
        public bool bit_GetRefNumOnReg { get; set; }
        public bool bit_ShowEnrollmentForm { get; set; }
        public string var_Message { get; set; }
        public string var_PayPalID { get; set; }
        public bool bit_PayOnRegistration { get; set; }
        public string var_PayPalToken { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_RegPPaymentTypes> tbl_RegPPaymentTypes { get; set; }
    }
}
