//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Locations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Locations()
        {
            this.tbl_LPLocations = new HashSet<tbl_LPLocations>();
            this.tbl_LPMeetingDates = new HashSet<tbl_LPMeetingDates>();
        }
    
        public int int_LocationID { get; set; }
        public int int_DistrictID { get; set; }
        public string var_LocationName { get; set; }
        public string var_StreetAddress { get; set; }
        public string var_City { get; set; }
        public string var_State { get; set; }
        public string var_Zip { get; set; }
        public string var_Phone { get; set; }
        public string var_Contact { get; set; }
        public bool bit_UseMap { get; set; }
        public string var_Directions { get; set; }
        public string var_Description { get; set; }
        public bool bit_UseYahooTravel { get; set; }
        public string var_LocationCode { get; set; }
        public bool bit_Active { get; set; }
    
        public virtual tbl_Districts tbl_Districts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LPLocations> tbl_LPLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LPMeetingDates> tbl_LPMeetingDates { get; set; }
    }
}
