//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FollowUps
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_FollowUps()
        {
            this.tbl_LPFollowUps = new HashSet<tbl_LPFollowUps>();
        }
    
        public int int_FollowUpID { get; set; }
        public string var_FollowUpName { get; set; }
        public string var_FollowUpCode { get; set; }
        public int int_DistrictID { get; set; }
        public int int_Order { get; set; }
        public bool bit_Active { get; set; }
    
        public virtual tbl_Districts tbl_Districts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LPFollowUps> tbl_LPFollowUps { get; set; }
    }
}
