//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CourseCodes
    {
        public int int_CourseCodeID { get; set; }
        public string var_CourseCodeName { get; set; }
        public string var_CourseCode { get; set; }
        public int int_DistrictID { get; set; }
        public int int_Order { get; set; }
        public bool bit_Active { get; set; }
        public int int_CourseAdminID { get; set; }
        public string var_ShortName { get; set; }
        public int int_SequenceNumber { get; set; }
        public bool bit_CanRetake { get; set; }
        public bool bit_CanRetakeForCredit { get; set; }
    
        public virtual tbl_Districts tbl_Districts { get; set; }
    }
}
