//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Prefs
    {
        public int int_PrefID { get; set; }
        public int int_UserID { get; set; }
        public int int_ActivityID { get; set; }
        public int int_ProgramID { get; set; }
        public int int_DistrictID { get; set; }
        public string var_Group { get; set; }
        public string var_Name { get; set; }
        public string var_Value { get; set; }
    
        public virtual tbl_Districts tbl_Districts { get; set; }
        public virtual tbl_UserProfile tbl_UserProfile { get; set; }
    }
}
