//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PDFXsl
    {
        public long int_PDFId { get; set; }
        public string var_Type { get; set; }
        public string var_SQL { get; set; }
        public string var_XSL { get; set; }
        public string var_Parameters { get; set; }
        public string var_Data { get; set; }
        public Nullable<long> int_DistrictId { get; set; }
        public string var_DistrictState { get; set; }
    }
}
