//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TeamThreads
    {
        public int int_TeamThreadID { get; set; }
        public int int_TeamTopicID { get; set; }
        public string var_Thread { get; set; }
        public int int_UserID { get; set; }
        public System.DateTime dt_Posted { get; set; }
        public int int_Reads { get; set; }
    
        public virtual tbl_UserProfile tbl_UserProfile { get; set; }
    }
}
