//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FTEStats
    {
        public int int_FTEStatsID { get; set; }
        public string var_StateCode { get; set; }
        public string var_StateName { get; set; }
        public int int_FTECount { get; set; }
    }
}
