//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ReportTables
    {
        public int int_ReportTableID { get; set; }
        public string var_Name { get; set; }
        public string var_DisplayName { get; set; }
        public bool bit_SysAdminOnly { get; set; }
        public bool bit_IsConnector { get; set; }
        public bool bit_MLP { get; set; }
        public bool bit_WebReg { get; set; }
        public bool bit_ContentCustomer { get; set; }
    }
}
