//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_RegCourseProviders
    {
        public int int_RegProviderID { get; set; }
        public int int_DistrictID { get; set; }
        public string var_RegProviderName { get; set; }
        public string var_RegProviderPath { get; set; }
        public Nullable<short> var_RegProviderType { get; set; }
        public string var_RegProviderURLPath { get; set; }
        public string var_ShortName { get; set; }
        public string var_SWAuthenticationID { get; set; }
    
        public virtual tbl_Districts tbl_Districts { get; set; }
    }
}
