//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Activities
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Activities()
        {
            this.tbl_ABuildings = new HashSet<tbl_ABuildings>();
            this.tbl_ACategories = new HashSet<tbl_ACategories>();
            this.tbl_AContent = new HashSet<tbl_AContent>();
            this.tbl_ActivityEvents = new HashSet<tbl_ActivityEvents>();
            this.tbl_ADepartments = new HashSet<tbl_ADepartments>();
            this.tbl_ADistricts = new HashSet<tbl_ADistricts>();
            this.tbl_AdminLog = new HashSet<tbl_AdminLog>();
            this.tbl_AEvalMethods = new HashSet<tbl_AEvalMethods>();
            this.tbl_AExpenses = new HashSet<tbl_AExpenses>();
            this.tbl_AFollowUps = new HashSet<tbl_AFollowUps>();
            this.tbl_AGrades = new HashSet<tbl_AGrades>();
            this.tbl_AGroups = new HashSet<tbl_AGroups>();
            this.tbl_AInstructors = new HashSet<tbl_AInstructors>();
            this.tbl_ALocations = new HashSet<tbl_ALocations>();
            this.tbl_AMeetingDates = new HashSet<tbl_AMeetingDates>();
            this.tbl_AObjectives = new HashSet<tbl_AObjectives>();
            this.tbl_APlans = new HashSet<tbl_APlans>();
            this.tbl_APreRequisites = new HashSet<tbl_APreRequisites>();
            this.tbl_APromoCodes = new HashSet<tbl_APromoCodes>();
            this.tbl_APurposes = new HashSet<tbl_APurposes>();
            this.tbl_ARegOptions = new HashSet<tbl_ARegOptions>();
            this.tbl_AStandards = new HashSet<tbl_AStandards>();
            this.tbl_AUsers = new HashSet<tbl_AUsers>();
            this.tbl_Files = new HashSet<tbl_Files>();
        }
    
        public int int_ActivityID { get; set; }
        public string var_ActivityTitle { get; set; }
        public string var_ActivityDesc { get; set; }
        public int int_DistrictID { get; set; }
        public int int_ProviderID { get; set; }
        public int int_ActivityFormatID { get; set; }
        public int int_PaymentFormatID { get; set; }
        public int int_CCatalogID { get; set; }
        public int int_EventID { get; set; }
        public string var_Type { get; set; }
        public int int_InstructorUserID { get; set; }
        public string var_InstructorName { get; set; }
        public Nullable<System.DateTime> dt_Date { get; set; }
        public Nullable<System.DateTime> dt_StartDate { get; set; }
        public Nullable<System.DateTime> dt_EndDate { get; set; }
        public string var_MeetingDates { get; set; }
        public Nullable<System.DateTime> dt_DateExpired { get; set; }
        public string var_URL { get; set; }
        public int int_MaxUsers { get; set; }
        public bool bit_ApprovalRequired { get; set; }
        public bool bit_UserCanEdit { get; set; }
        public bool bit_QuickApprove { get; set; }
        public float rl_ActivityHours { get; set; }
        public float rl_Credits { get; set; }
        public string var_Comments { get; set; }
        public Nullable<int> int_FormID { get; set; }
        public string var_ConferenceLocation { get; set; }
        public string var_Audience { get; set; }
        public string var_Level { get; set; }
        public decimal mon_SubscriberFee { get; set; }
        public decimal mon_NonSubscriberFee { get; set; }
        public System.DateTime dt_DateAdded { get; set; }
        public System.DateTime dt_DateUpdated { get; set; }
        public bool bit_Archived { get; set; }
        public bool bit_Future2 { get; set; }
        public bool bit_Future3 { get; set; }
        public string var_Future1 { get; set; }
        public string var_SessionCode { get; set; }
        public string var_Future3 { get; set; }
        public float rl_Future1 { get; set; }
        public float rl_Future2 { get; set; }
        public float rl_Future3 { get; set; }
        public int int_MinUsers { get; set; }
        public int int_CourseCodeID { get; set; }
        public int int_Future3 { get; set; }
        public bool bit_ShowSubscriberFee { get; set; }
        public Nullable<System.DateTime> dt_StartShowing { get; set; }
        public Nullable<System.DateTime> dt_StopShowing { get; set; }
        public string var_ProviderName { get; set; }
        public string var_CourseCode { get; set; }
        public int int_WaitListMax { get; set; }
        public bool bit_WaitListAuto { get; set; }
        public int int_EvalFormID { get; set; }
        public int int_ConfTimeSlotID { get; set; }
        public int int_ProgramID { get; set; }
        public bool bit_TeamRoomDiscussEnabled { get; set; }
        public bool bit_TeamRoomFilesEnabled { get; set; }
        public bool bit_PreRegOnly { get; set; }
        public string var_DescriptionLarge { get; set; }
        public int int_ProposalLPID { get; set; }
        public string var_Annotations { get; set; }
        public Nullable<int> int_OwnerID { get; set; }
        public string var_ExternalID { get; set; }
        public Nullable<int> int_FeaturedPriority { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ABuildings> tbl_ABuildings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ACategories> tbl_ACategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AContent> tbl_AContent { get; set; }
        public virtual tbl_Districts tbl_Districts { get; set; }
        public virtual tbl_Forms tbl_Forms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ActivityEvents> tbl_ActivityEvents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ADepartments> tbl_ADepartments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ADistricts> tbl_ADistricts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AdminLog> tbl_AdminLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AEvalMethods> tbl_AEvalMethods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AExpenses> tbl_AExpenses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AFollowUps> tbl_AFollowUps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AGrades> tbl_AGrades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AGroups> tbl_AGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AInstructors> tbl_AInstructors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ALocations> tbl_ALocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AMeetingDates> tbl_AMeetingDates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AObjectives> tbl_AObjectives { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_APlans> tbl_APlans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_APreRequisites> tbl_APreRequisites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_APromoCodes> tbl_APromoCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_APurposes> tbl_APurposes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ARegOptions> tbl_ARegOptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AStandards> tbl_AStandards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AUsers> tbl_AUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Files> tbl_Files { get; set; }
    }
}
