//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PromoCodes
    {
        public int int_PromoCodeID { get; set; }
        public string var_PromoCode { get; set; }
        public string var_UnitType { get; set; }
        public float rl_Units { get; set; }
        public Nullable<System.DateTime> dt_Expires { get; set; }
        public bool bit_ShowOnRegistration { get; set; }
        public bool bit_IncludeReturnUrl { get; set; }
        public string var_RegistrationMessage { get; set; }
        public string var_PromoCodeRequestUrl { get; set; }
        public bool bit_ApplyToSubscribers { get; set; }
        public int int_DistrictID { get; set; }
    
        public virtual tbl_Districts tbl_Districts { get; set; }
    }
}
