//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Providers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Providers()
        {
            this.tbl_DProviders = new HashSet<tbl_DProviders>();
            this.tbl_DRegionalProviders = new HashSet<tbl_DRegionalProviders>();
        }
    
        public int int_ProviderID { get; set; }
        public int int_DistrictIDOLD { get; set; }
        public string var_ProviderName { get; set; }
        public string var_ProviderShortName { get; set; }
        public string var_ProviderAddress1 { get; set; }
        public string var_ProviderAddress2 { get; set; }
        public string var_ProviderCity { get; set; }
        public string var_ProviderState { get; set; }
        public string var_ProviderZip { get; set; }
        public string var_ProviderContact { get; set; }
        public string var_ProviderPhone { get; set; }
        public string var_URL { get; set; }
        public string var_AccountNumber { get; set; }
        public string var_ProviderDescription { get; set; }
        public string var_Directions { get; set; }
        public bool bit_PDEReport { get; set; }
        public bool bit_IsSystemProvider { get; set; }
        public bool bit_UserCanPrintCert { get; set; }
        public string var_ProviderContactJobTitle { get; set; }
        public string var_ProviderTTY { get; set; }
        public string var_ProviderLetterHeadPath { get; set; }
        public string var_ProviderFax { get; set; }
        public int int_UserID { get; set; }
        public bool bit_UseAPI { get; set; }
        public string var_APIType { get; set; }
        public string var_APIParameters { get; set; }
        public int int_APIPassingScore { get; set; }
        public bool bit_APIAutoEnroll { get; set; }
        public bool bit_APICreateAccount { get; set; }
        public string var_CertStyle { get; set; }
        public string var_LicenseID { get; set; }
        public int int_PassingScore { get; set; }
        public bool bit_AutoComplete { get; set; }
        public string var_ContactEmail { get; set; }
        public int int_RegistrationFormID { get; set; }
        public string var_StateCode { get; set; }
        public bool bit_AutoRollover { get; set; }
        public Nullable<System.DateTime> dt_AutoRolloverStartDate { get; set; }
        public Nullable<System.DateTime> dt_AutoRolloverEndDate { get; set; }
        public Nullable<System.DateTime> dt_AutoRolloverDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DProviders> tbl_DProviders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DRegionalProviders> tbl_DRegionalProviders { get; set; }
    }
}
