//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OASYSAdHocReports
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_OASYSAdHocReports()
        {
            this.tbl_Districts = new HashSet<tbl_Districts>();
        }
    
        public int int_AdHocReportID { get; set; }
        public string nvar_AdHocReportName { get; set; }
        public string nvar_AdHocReportDescription { get; set; }
        public string nvar_AdHocReportSQL { get; set; }
        public bool bit_IsDeleted { get; set; }
        public bool bit_RequiresRegionOwner { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Districts> tbl_Districts { get; set; }
    }
}
