//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AMeetingDates
    {
        public int int_AMeetingDateID { get; set; }
        public int int_ActivityID { get; set; }
        public System.DateTime dt_Date { get; set; }
        public Nullable<System.DateTime> dt_StartDateTime { get; set; }
        public Nullable<System.DateTime> dt_EndDateTime { get; set; }
        public string var_Location { get; set; }
        public int int_LocationID { get; set; }
        public int int_DurationHours { get; set; }
        public int int_DurationMinutes { get; set; }
        public int int_Meeting { get; set; }
        public bool bit_SubNeeded { get; set; }
        public Nullable<System.DateTime> dt_SubStartDateTime { get; set; }
        public Nullable<System.DateTime> dt_SubEndDateTime { get; set; }
        public string var_SubShift { get; set; }
        public int int_SubBuildingID { get; set; }
    
        public virtual tbl_Activities tbl_Activities { get; set; }
    }
}
