//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CCourses
    {
        public int int_CCourseID { get; set; }
        public string var_ACRONYM { get; set; }
        public string var_TITLE { get; set; }
        public string var_URL { get; set; }
        public int int_OBJCOUNT { get; set; }
        public string var_MLHexID { get; set; }
        public string var_PRODCODE { get; set; }
    }
}
