//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OASYSArtifacts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_OASYSArtifacts()
        {
            this.tbl_OASYSArtifactGroups = new HashSet<tbl_OASYSArtifactGroups>();
            this.tbl_OASYSRubricCriteria = new HashSet<tbl_OASYSRubricCriteria>();
        }
    
        public int int_ArtifactId { get; set; }
        public string nvar_ArtifactName { get; set; }
        public string nvar_ArtifactDescription { get; set; }
        public string nvar_ArtifactFileName { get; set; }
        public System.DateTime date_DateUploaded { get; set; }
        public int int_userId { get; set; }
        public bool bit_IsDeleted { get; set; }
        public Nullable<int> int_UploadUserId { get; set; }
        public Nullable<int> int_SectionId { get; set; }
        public Nullable<int> int_EvaluationId { get; set; }
        public Nullable<int> int_InstanceId { get; set; }
        public int int_ArtifactFileType { get; set; }
        public string nvar_RemoteSysName { get; set; }
        public string nvar_ArtifactStatement { get; set; }
        public bool bit_AdminOnly { get; set; }
    
        public virtual tbl_UserProfile tbl_UserProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSArtifactGroups> tbl_OASYSArtifactGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSRubricCriteria> tbl_OASYSRubricCriteria { get; set; }
    }
}
