//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UserUpdateEvents
    {
        public long Id { get; set; }
        public int UserID { get; set; }
        public int DistrictId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public bool Active { get; set; }
        public string EmployeeID { get; set; }
        public string Action { get; set; }
        public System.DateTime EventTime { get; set; }
        public Nullable<System.DateTime> SentToUserService { get; set; }
        public Nullable<int> PreviousDistrictId { get; set; }
        public Nullable<System.Guid> OrgPersonId { get; set; }
    
        public virtual tbl_UserUpdateEventsQueue tbl_UserUpdateEventsQueue { get; set; }
    }
}
