//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Purposes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Purposes()
        {
            this.tbl_APurposes = new HashSet<tbl_APurposes>();
            this.tbl_LPBank = new HashSet<tbl_LPBank>();
            this.tbl_LPPurposes = new HashSet<tbl_LPPurposes>();
        }
    
        public int int_PurposeID { get; set; }
        public int int_DistrictID { get; set; }
        public string var_PurposeName { get; set; }
        public string var_PurposeShortName { get; set; }
        public string var_PurposeDesc { get; set; }
        public string var_HoursOrCredits { get; set; }
        public float rl_CreditToHourConversion { get; set; }
        public int int_Order { get; set; }
        public System.DateTime dt_StartDate { get; set; }
        public System.DateTime dt_EndDate { get; set; }
        public bool bit_Certification { get; set; }
        public bool bit_Active { get; set; }
        public bool bit_Salary { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_APurposes> tbl_APurposes { get; set; }
        public virtual tbl_Districts tbl_Districts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LPBank> tbl_LPBank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LPPurposes> tbl_LPPurposes { get; set; }
    }
}
