//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OASYSArtifactGroups
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_OASYSArtifactGroups()
        {
            this.tbl_OASYSArtifacts = new HashSet<tbl_OASYSArtifacts>();
            this.tbl_OASYSTypes = new HashSet<tbl_OASYSTypes>();
        }
    
        public int int_ArtifactGroupId { get; set; }
        public string nvar_ArtifactGroupName { get; set; }
        public string nvar_ArtifactGroupDescription { get; set; }
        public int int_DistrictId { get; set; }
        public int int_ArtifactGroupKind { get; set; }
        public bool bit_IsDeleted { get; set; }
    
        public virtual tbl_Districts tbl_Districts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSArtifacts> tbl_OASYSArtifacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSTypes> tbl_OASYSTypes { get; set; }
    }
}
