//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OASYSRubricLevels
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_OASYSRubricLevels()
        {
            this.tbl_OASYSRubricDescriptors = new HashSet<tbl_OASYSRubricDescriptors>();
        }
    
        public int int_LevelID { get; set; }
        public int int_RubricID { get; set; }
        public int int_LevelValue { get; set; }
        public string nvar_LevelName { get; set; }
        public Nullable<decimal> dec_LevelScore { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OASYSRubricDescriptors> tbl_OASYSRubricDescriptors { get; set; }
        public virtual tbl_OASYSRubrics tbl_OASYSRubrics { get; set; }
    }
}
