//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OASYSConversionSheetRanges
    {
        public int int_ConversionSheetRangeID { get; set; }
        public int int_ConversionSheetID { get; set; }
        public decimal dec_MinValue { get; set; }
        public decimal dec_MaxValue { get; set; }
        public string nvar_Value { get; set; }
        public string nvar_Rating { get; set; }
    
        public virtual tbl_OASYSConversionSheets tbl_OASYSConversionSheets { get; set; }
    }
}
