//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoklaTheMok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temptbl_OASYSSections_FPS1235_1
    {
        public int ID { get; set; }
        public Nullable<int> int_SectionID { get; set; }
        public string nvar_Config { get; set; }
    }
}
